Expand display options - refactor data structure [MAILPOET-3072]
mailpoet/mailpoet pull request #3006
Opened 2020-08-28 07:00 UTC by pavel-mailpoet

[MAILPOET-3072]

@veljkho This is just a prepare step, nothing is changing during this ticket. It is just a refactor. Please test all the form placement options to see if nothing breaks. It should also migrate old forms to the new structure so please test some existing and some new forms. You need to adjust the version number in your database again.

2020-08-31 07:46 UTC, costasovo requested changes
Looks Good! I just think that with this change we also need to update form templates we already have.
We probably need just to remove these lines from all templates: https://github.com/mailpoet/mailpoet/blob/master/lib/Form/Templates/Templates/Template10BelowPages.php#L179-L191

and should also remove placement styles if they are set to default values like [these](https://github.com/mailpoet/mailpoet/blob/master/lib/Form/Templates/Templates/Template10BelowPages.php#L199-L228). If there are some non-default values we need to rewrite those to new data structure.

2020-08-31 07:46 UTC, costasovo commented on lib/Config/Populator.php
> +          'enabled' => $settings['form_placement_popup_enabled'],
I see we don't unset these outdated properties in migration. They will be removed on form save. Am I correct?

2020-08-31 12:10 UTC, costasovo commented on lib/Config/Populator.php
> +      if (isset($settings['slide_in_form_position'])) unset($settings['slide_in_form_position']);
I think we need to add unset also for outdated placement styles properties:
below_post_styles
slide_in_styles
fixed_bar_styles
popup_styles
other_styles

2020-08-31 12:32 UTC, costasovo approved these changes

2020-08-31 14:39 UTC, veljkho requested changes
Some problems occured
**1.a**: When I try to change form's width values in the Preview screen, nothing has changed in the preview actually (it's frozen)
**1.b**: The same happens if I try to move form from left-righ or top-bottom (slide-in, fixedbar)
**2.a**: Also, if I publish the form with fixed bar - on the front end it will be centered and not on the top as it should
**2.b**: And, if I try to publish slide-in (right), it will be on the front end something like in the middle of the screen - [screenshot for both 2 a & b](https://i.imgur.com/wfNpSHD.png)
**3**. In my local environment, blank page for the whole form editor is present if I click on Style expandable block in the settings (but this is not present on my online environment, at prod.qawp.net)

All issues except 3rd one can be reproduced at prod.qawp.net (admin / arabica99!)
I changed db_version in database to 3.44.0 and performed deactivation/activation.

2020-09-01 11:22 UTC, costasovo approved these changes

2020-09-01 14:23 UTC, veljkho requested changes
Unfortunately,
I have found another issue, but it probably existed already in previous testing.
In Forms list page, all forms are Type: Others (widget), no matter what type you've set inside. This is for both new and old forms. Good is that issue is not present inside form editor or on the front end (so issue in listing only).

2020-09-02 08:55 UTC, costasovo approved these changes

2020-09-02 11:17 UTC, veljkho approved these changes

2020-09-02 11:17 UTC, merged