Fix too much space at the end of form [MAILPOET-3090]
mailpoet/mailpoet pull request #3021
Opened 2020-09-02 11:31 UTC by pavel-mailpoet

[MAILPOET-3090]

2020-09-02 12:23 UTC, costasovo commented on lib/Form/Templates/FormTemplate.php
> +.last .mailpoet_paragraph {
I think it would be nicer to have it in one place here https://github.com/mailpoet/mailpoet/blob/master/lib/Form/Util/Styles.php#L116

2020-09-03 09:28 UTC, costasovo submitted a review, later dismissed

2020-09-03 12:02 UTC, veljkho requested changes
We have new issue now. If we place inside columns block, blocks like email, subscribe, first name or image.. they will be without space at bottom of each block, looking merged together.. on both mobile and web view.
[Screenshot](https://i.imgur.com/TEAdRKO.png)

2020-09-07 15:22 UTC, costasovo approved these changes

2020-09-08 12:18 UTC, veljkho requested changes
Issue partially verified.
We have still problem on mobile, but in this case:
- Column block 50-50
- Place email block in left place, subscribe button in right place (inside that column block)
- Preview it in mobile and observe the same issue with missing spacing bottom

All other verified

2020-09-09 08:06 UTC, costasovo approved these changes

2020-09-09 09:11 UTC, veljkho approved these changes

2020-09-09 09:11 UTC, merged