Form templates - Batch 3 [MAILPOET-3076]
mailpoet/mailpoet pull request #3027
Opened 2020-09-04 07:58 UTC by costasovo

### Note for QA

When testing this locally you need to turn off CDN (`define('MAILPOET_USE_CDN', false);`) to see form assets.

2020-09-07 07:55 UTC, pavel-mailpoet requested changes

2020-09-07 07:55 UTC, pavel-mailpoet commented on lib/Form/Templates/Templates/Template7FixedBar.php
> +                  'content' => _x('<span style="font-family: Cairo" data-font="Cairo" class="mailpoet-has-font">Let us do the hard work for you. Sign up to receive our latest deals directly in your i
Two things here.
1) Should we clear the link here? I think the idea is for the user to add their own privacy policy.
2) Could we not use this syntax? `We\'ll` It is hard to search for it when you need to do a full-text search in the source code.

2020-09-07 07:56 UTC, pavel-mailpoet requested changes
See my comment

2020-09-10 14:17 UTC, pavel-mailpoet approved these changes

2020-09-14 12:04 UTC, costasovo commented
@pavel-mailpoet I added 2 more commits with some fixes in the template data.

2020-09-14 12:08 UTC, pavel-mailpoet approved these changes

2020-09-14 12:22 UTC, veljkho approved these changes

2020-09-14 12:22 UTC, merged