Redesign last step in email creation [MAILPOET-3089] [MAILPOET-2790]
mailpoet/mailpoet pull request #3056
Opened 2020-09-23 14:30 UTC by NeosinneR

[MAILPOET-3089] [MAILPOET-2790]

[MAILPOET-3089]: https://mailpoet.atlassian.net/browse/MAILPOET-3089
[MAILPOET-2790]: https://mailpoet.atlassian.net/browse/MAILPOET-2790

2020-09-24 13:02 UTC, wxa requested changes
The biggest issue is validation failures do not stop a form from saving, allowing to save an email without subject/list specified, or causing SQL errors due to very long data etc.

2020-09-24 13:59 UTC, NeosinneR commented on assets/js/src/newsletters/automatic_emails.jsx
> +            'data-parsley-required': true,
Fixed, added regular HTML `maxlength` attribute, which won't allow entering any more characters

2020-09-24 14:05 UTC, wxa commented on assets/js/src/newsletters/automatic_emails.jsx
> +            'data-parsley-required': true,
You've fixed it for preheader, but not for subject.

2020-09-24 14:18 UTC, NeosinneR commented on assets/js/src/newsletters/automatic_emails.jsx
> +            'data-parsley-required': true,
Yeah, sorry, completely missed that you were talking about both preview and subject. Now, the subject also has `maxlength` added.

2020-09-24 14:20 UTC, NeosinneR commented on assets/js/src/newsletters/automatic_emails.jsx
> +            'data-parsley-maxlength': 250,
That's by design. The two lines are enough for the max 250 characters. I haven't found any research on using new lines, but in a [SO](https://stackoverflow.com/questions/47166603/why-is-there-a-line-break-in-my-email-preview-text-in-ios-mail-app) post the multiline preview looks fine in the iOS Mail app. I however added a note in the tooltip (proofread by Laura), that we recommend using it on a single line and we'll see in the future if we receive any issues regarding this.

2020-09-27 20:39 UTC, wxa commented
Subject validation error message is partially obstructed when the preheader field is highlighted in green or red:
![изображение](https://user-images.githubusercontent.com/9365088/94374449-02ed9e00-0115-11eb-8d4b-e036b3bdffb0.png)
Same with the sender name field:
![изображение](https://user-images.githubusercontent.com/9365088/94374528-932be300-0115-11eb-8cd1-bd38a5a90557.png)

2020-09-28 06:18 UTC, wxa approved these changes
Huge work, thanks!

2020-09-28 09:19 UTC, veljkho approved these changes

2020-09-28 09:19 UTC, merged