Form templates part 4 [MAILPOET-3190]
mailpoet/mailpoet pull request #3080
Opened 2020-10-01 14:12 UTC by costasovo

[MAILPOET-3190]

2020-10-01 14:21 UTC, pavel-mailpoet approved these changes

2020-10-01 15:44 UTC, veljkho requested changes
Some corrections needed:
- Priority List (Popup) - Display on all posts/pages radio buttons turned ON by default
- I forgot to add form editor's custom css `.wp-block-column:not(:first-child),` to add padding inside editor only for the following forms: **Test 12 #Popup** & **Test 12 #SlideIn** only. So I added now and please copy/paste from mailpoet.info site.

2020-10-05 09:38 UTC, pavel-mailpoet requested changes

2020-10-05 09:38 UTC, pavel-mailpoet commented on lib/Form/Block/Heading.php
> +      $styles[] = 'line-height: 1.4;';
This overrides a value from custom css. I think we should use a different approach.

2020-10-05 10:22 UTC, pavel-mailpoet submitted a review, later dismissed

2020-10-05 12:21 UTC, pavel-mailpoet submitted a review, later dismissed

2020-10-05 13:36 UTC, pavel-mailpoet submitted a review, later dismissed

2020-10-05 15:24 UTC, veljkho approved these changes

2020-10-05 15:24 UTC, merged