Add cart contents block to email templates [MAILPOET-3182]
mailpoet/mailpoet pull request #3141
Opened 2020-10-28 16:24 UTC by pavel-mailpoet

[MAILPOET-3182]

2020-10-28 20:21 UTC, wxa requested changes
Please rename the templates according to specs 1b, 2b.

2020-10-28 20:21 UTC, wxa commented on lib/Config/PopulatorData/Templates/Fitness.php
> +    return $this->template_image_url . '/fitness-thumbnail.20201028.jpg';
We already have the template name as a folder in `$this->template_image_url`, so I think adding a name to the thumbnail file is redundant.

2020-10-29 09:17 UTC, wxa approved these changes
Both templates had the name "Abandoned Cart - Kids", but I fixed that. Approved.

2020-10-29 14:43 UTC, veljkho approved these changes

2020-10-29 14:43 UTC, merged