Redesign UI fixes [MAILPOET-3284]
mailpoet/mailpoet pull request #3160
Opened 2020-11-11 15:45 UTC by NeosinneR

[MAILPOET-3284]

2020-11-11 17:44 UTC, lysyjan approved these changes

2020-11-12 09:49 UTC, veljkho requested changes
I see [this notice](https://i.imgur.com/A2XVAar.png) is without spacing at the bottom.

2020-11-12 12:33 UTC, NeosinneR commented
@veljkho fixed

2020-11-12 14:02 UTC, veljkho approved these changes

2020-11-12 14:02 UTC, merged