Remove premium autoinstall [MAILPOET-3315]
mailpoet/mailpoet pull request #3194
Opened 2020-11-25 14:36 UTC by pavel-mailpoet

[MAILPOET-3315]

2020-11-25 15:19 UTC, costasovo requested changes
Looks good! I have just 3 small remarks.

2020-11-25 15:19 UTC, costasovo commented on assets/js/src/settings/pages/key_activation/messages/premium_messages.tsx
> +import Button from '../../../../common/button/button';
Can you please path from the root instead of a relative path?

2020-11-25 15:19 UTC, costasovo commented on views/settings.html
>      'premiumTabPremiumActivatingMessage': __('MailPoet Premium plugin is being activated', 'mailpoet'),
I think we no longer need these 2 strings.

2020-11-25 15:19 UTC, costasovo commented on views/settings.html
> +    'premiumTabPremiumActivateMessage': __('Download MailPoet Premium plugin', 'mailpoet'),
Can we use text stubs that fit a bit better? I find these two a bit confusing.
For example `premiumTabPremiumNotInstalledMessage` `premiumTabPremiumDownloadMessage `

2020-11-26 07:44 UTC, costasovo approved these changes

2020-11-26 09:38 UTC, veljkho requested changes
Sorry, there was missing the 3rd case in the specs of the Jira ticket. I now updated the 3rd case when Premium is installed but not activated, we should show a different message without a button.

2020-11-26 10:16 UTC, veljkho approved these changes

2020-11-26 10:16 UTC, merged