Refactor dynamic segments listings to doctrine [MAILPOET-3164]
mailpoet/mailpoet pull request #3252
Opened 2021-01-08 12:35 UTC by pavel-mailpoet

[MAILPOET-3164]

2021-01-08 13:18 UTC, costasovo requested changes
I found one issue that needs to be fixed and have one comment. Otherwise looks good.

2021-01-08 13:18 UTC, costasovo commented on lib/Segments/SegmentListingRepository.php
>      }
The listing repository is used for both static and dynamic segments and WooCommerce segment is added dynamically based on WooCommerce plugin status. This causes that when WooCommerce plugin is active we display WooCommerce segment in both static and dynamic segment lists

2021-01-08 13:18 UTC, costasovo commented on lib/Segments/DynamicSegments/DynamicSegmentsListingRepository.php
> +  protected $types = [SegmentEntity::TYPE_DYNAMIC];
I think that instead of inheritance we could pass this as an argument or via a constructor or a setter.

2021-01-08 15:15 UTC, costasovo approved these changes

2021-01-08 15:32 UTC, costasovo requested changes
Oh! I've just checked the related [Jira issue](https://mailpoet.atlassian.net/browse/MAILPOET-3164) and it seems that you did a bit different stuff that is in the spec. The name of the Jira card is probably misleading. This task is about removing the rest of the dynamic segments old model usages.
It is used in various places for fetching a list of segments please see the spec. all usages are listed there.

2021-01-11 11:17 UTC, costasovo approved these changes

2021-01-11 12:24 UTC, veljkho approved these changes

2021-01-11 12:24 UTC, merged