Fix missing statistics link in WooCommerce listing [MAILPOET-3318]
mailpoet/mailpoet pull request #3275
Opened 2021-01-19 13:05 UTC by lysyjan

[MAILPOET-3318]

2021-01-19 17:42 UTC, wxa approved these changes

2021-01-20 09:38 UTC, veljkho requested changes
Not verified
There's still a missing Statistics link when you hover any newsletter title in Woo's tab.
I see that Opened/Clicked column is present now, which is good. I should have attached the screenshot as well in Jira, this is [the missing link](https://d.pr/i/XJATZv).

2021-01-20 09:57 UTC, veljkho commented
It was a problem with my cache, ticket implemented properly. Verifying it and merging.

2021-01-20 09:58 UTC, veljkho approved these changes

2021-01-20 09:58 UTC, merged