Refactor segment lists fetching to Doctrine [MAILPOET-3164]
mailpoet/mailpoet pull request #3278
Opened 2021-01-20 16:15 UTC by costasovo

[MAILPOET-3164]

### Note for QA:
This change affects all select inputs where a user picks a segment or multiple segments on following pages:

- /wp-admin/admin.php?page=mailpoet-export
- /wp-admin/admin.php?page=mailpoet-import
- /wp-admin/admin.php?page=mailpoet-form-editor
- /wp-admin/admin.php?page=mailpoet-subscribers
- /wp-admin/admin.php?page=mailpoet-settigns
- /wp-admin/admin.php?page=mailpoet-newsletters (send page and automatic newsletters configuration)

2021-01-21 12:19 UTC, lysyjan submitted a review, later dismissed
It looks like great work

2021-01-21 14:47 UTC, veljkho requested changes
There is some issue:
Lists with 0 subscribers are with improper design in select2 fields, like in [this example](https://d.pr/i/MFNeAb). Other lists with at least 1 subscribers are good.

2021-01-22 11:08 UTC, costasovo commented
@lysyjan I've added 2 commits with a fix of Proptypes warnings I was getting on the settings page (this one was present before my changes) and a fix for formatting subscriber counts within inputs.

2021-01-22 14:00 UTC, lysyjan approved these changes

2021-01-25 08:17 UTC, veljkho approved these changes

2021-01-25 08:17 UTC, merged