Export subscription consent evidence [MAILPOET-3393]
mailpoet/mailpoet pull request #3326
Opened 2021-02-16 10:05 UTC by pavel-mailpoet

[MAILPOET-3393]

2021-02-17 14:31 UTC, lysyjan submitted a review, later dismissed

2021-02-18 09:36 UTC, veljkho requested changes
There are some issues in this PR:
- Unable to `Select all ...` `Deselect all ...`. Unclickable issue
- `Subscription time` and `Confirmation time` are always with literally the same values. Shouldn't they be different a bit? The time when subscribed and confirmed, that's how I understood.

2021-02-19 08:40 UTC, lysyjan approved these changes

2021-03-01 11:29 UTC, veljkho requested changes
A new issue has arrived. Subscription time is not preselected.
The rest is verified.

Another potential issue is not clear to me. The values for `subscription time` & `confirmation time` [are always the same](https://d.pr/i/pWYoM3) no matter if user subscribes again to another list, or unsubscribe and then re-subscribe (to any list). The system counts it only once and remembers the first time user subscribed/confirmed. For all lists.

2021-03-02 08:36 UTC, lysyjan approved these changes

2021-03-02 15:39 UTC, veljkho approved these changes

2021-03-02 15:39 UTC, merged