WooCommerce stable version [MAILPOET-3330]
mailpoet/mailpoet pull request #3327
Opened 2021-02-16 13:30 UTC by pavel-mailpoet

[MAILPOET-3330]

Check this build for the oldest acceptance test: https://app.circleci.com/pipelines/github/mailpoet/mailpoet/5767/workflows/70afbf10-a487-4cee-bc95-08ee6c855966

2021-02-17 13:03 UTC, wxa requested changes
We now use 5.0.0 for regular builds and 4.0.1 for the "oldest" one, but where's the latest WooCommerce for the nightly build? The task says "Keep the latest version for the nightly run".

2021-02-18 12:22 UTC, pavel-mailpoet commented
Here is the build with the latest and oldest version: https://app.circleci.com/pipelines/github/mailpoet/mailpoet/5798/workflows/c1f527c6-b73f-4a4a-9495-da2022ee11c5

The latest version is 5.0.0 so not much to see there.

2021-02-18 13:07 UTC, wxa approved these changes
Thank you!

2021-03-01 09:35 UTC, veljkho approved these changes

2021-03-01 09:36 UTC, merged