Connecting segments [MAILPOET-3212]
mailpoet/mailpoet pull request #3390
Opened 2021-03-16 15:07 UTC by pavel-mailpoet

[MAILPOET-3212]

[MAILPOET-3212]: https://mailpoet.atlassian.net/browse/MAILPOET-3212

2021-03-19 12:21 UTC, costasovo requested changes
Good job! I found one issue that needs to be addressed.

2021-03-19 12:21 UTC, costasovo commented on lib/Segments/SegmentSubscribersRepository.php
> +    } elseif ($segment instanceof SegmentEntity) {
This change will cause that this method will not work correctly when $segmentEntity is not passed an it was expected to work. It is used here https://github.com/mailpoet/mailpoet/blob/7e0c718683e98d3c26fb14ef0995a6a23d868ba4/lib/Segments/SegmentSubscribersRepository.php#L80

And it results in broken functionality for showing subscriber count during creation of a dynamic segment.

2021-03-23 08:44 UTC, costasovo approved these changes
Good job!

2021-03-23 12:27 UTC, veljkho approved these changes

2021-03-23 14:58 UTC, merged