Layout components updates [MAILPOET-3503]
mailpoet/mailpoet pull request #3397
Opened 2021-03-18 22:38 UTC by NeosinneR

[MAILPOET-3503]

2021-03-19 14:50 UTC, lysyjan requested changes

2021-03-19 14:50 UTC, lysyjan commented on assets/js/src/common/grid/centered_row.tsx
> +export default CenteredRow;
We want to avoid using export default, and we should use named exports everywhere.

2021-03-19 14:50 UTC, lysyjan commented on .eslintrc.ts.json
> +        "assets/js/src/common/grid/centered_row.tsx",
We shouldn't add more ignored files to this list. You created a new component that shouldn't be added to this long list.

2021-03-22 08:08 UTC, lysyjan approved these changes
Thanks

2021-03-22 11:02 UTC, veljkho approved these changes

2021-03-22 11:02 UTC, merged