Update dependencies [MAILPOET-3511]
mailpoet/mailpoet pull request #3418
Opened 2021-03-26 17:13 UTC by lysyjan

[MAILPOET-3511]

2021-03-29 07:02 UTC, pavel-mailpoet requested changes

2021-03-29 10:54 UTC, pavel-mailpoet submitted a review, later dismissed

2021-03-29 13:54 UTC, veljkho commented
Please resolve branch conflicts and reassign to me. Thanks.

2021-03-30 12:05 UTC, veljkho approved these changes

2021-03-30 12:05 UTC, merged