Mention Consent and Suppression lists in Subscriber Import [MAILPOET-3526]
mailpoet/mailpoet pull request #3458
Opened 2021-04-19 09:58 UTC by pavel-mailpoet

[MAILPOET-3526]

2021-04-19 12:16 UTC, lysyjan submitted a review, later dismissed

2021-04-21 11:36 UTC, veljkho requested changes
Can we move those KBs inside a Beacon? To be opened via Beacon, I thought this was by default for all KBs.

Otherwise, looks good and no issues found. 👍

2021-04-21 11:40 UTC, NeosinneR commented
@pavel-mailpoet I updated the specs with Beacon IDs

2021-04-22 08:28 UTC, lysyjan approved these changes

2021-04-22 08:31 UTC, veljkho approved these changes

2021-04-22 08:31 UTC, merged