Optimise tasks SQL query in inactive subscribers detection [MAILPOET-3582]
mailpoet/mailpoet pull request #3477
Opened 2021-04-27 09:24 UTC by costasovo

There are 2 optimizations in the PR. The first optimization is that the sub query for checking that a newsletter associated with a task has something tracked was moved from where clause to join so that it runs only once instead of for every line. The second was the removal `created_at` condition from the subquery.

We don’t necessarily need to use where `created_at` for statics open since we already restrict the sending task by the `processed_at` date and it is the `created_at` that forces the DB to scan multiple rows. It is impossible for a standard newsletter or post notification to have a record in opens stats before it was sent.  Automated and welcome emails have some opens logged further in the past so the check might not work correctly for sites using welcome emails that turned off tracking for some time and then turned it on again. I think it is something we can accept as a tradeof. 

[MAILPOET-3582]

2021-04-27 09:27 UTC, pavel-mailpoet requested changes

2021-04-27 09:27 UTC, pavel-mailpoet commented on lib/Subscribers/InactiveSubscribersController.php
>          $thresholdDateIso, $dayAgoIso, $thresholdDateIso
We need to remove one of the arguments.

2021-04-27 10:44 UTC, pavel-mailpoet approved these changes

2021-04-28 08:52 UTC, veljkho approved these changes

2021-04-28 08:52 UTC, merged