Segment clicked any [MAILPOET-3223]
mailpoet/mailpoet pull request #3478
Opened 2021-04-27 12:21 UTC by costasovo

[MAILPOET-3223]

2021-04-27 12:29 UTC, pavel-mailpoet approved these changes

2021-04-28 12:22 UTC, veljkho requested changes
Not verified
Point 1.d is not verified. I see subscribers as counted when clicking Unsubscribe or Manage Subscription links in newsletters. Those two links should be ignored.

2021-04-29 11:12 UTC, costasovo commented
@pavel-mailpoet I've added one new commit.

2021-04-29 11:20 UTC, pavel-mailpoet approved these changes

2021-04-29 11:21 UTC, pavel-mailpoet approved these changes

2021-04-29 14:32 UTC, veljkho approved these changes

2021-04-29 14:33 UTC, merged