Add throttling for a sending batch size [MAILPOET-3588]
mailpoet/mailpoet pull request #3490
Opened 2021-04-30 12:32 UTC by lysyjan

[MAILPOET-3588]

2021-04-30 13:14 UTC, costasovo requested changes
Good job! I have just a few remarks.

2021-04-30 13:14 UTC, costasovo commented on lib/Cron/Workers/SendingQueue/SendingThrottlingHandler.php
> +    if ($throttlingSettings['success_in_row'] === self::SUCCESS_THRESHOLD_TO_INCREASE) {
I would rather use `>=`. Right now === seems to be safe but we may introduce some changes in the future combined with the fact cron may run by accident in parallel and if we for some reason get over SUCCESS_THRESHOLD_TO_INCREASE we would never return to a bigger batch.

2021-04-30 13:14 UTC, costasovo commented on tests/integration/Cron/Workers/SendingQueue/SendingThrottlingHandlerTest.php
> +class SendingThrottlingHandlerTest extends \MailPoetTest {
I think we should add test cases for increasing batch size after certain amount of successes and maybe also that the lowest possible batch size is 1.

2021-04-30 14:04 UTC, costasovo approved these changes
👍

2021-05-03 16:39 UTC, veljkho approved these changes

2021-05-03 16:39 UTC, merged