Gracefully handle unsupported Email Editor blocks [MAILPOET-3437]
mailpoet/mailpoet pull request #3531
Opened 2021-05-25 08:32 UTC by pavel-mailpoet

[MAILPOET-3437]

2021-05-25 09:22 UTC, costasovo requested changes
The block works works as expected in the editor. I ran into an error when I tried form preview (https://d.pr/i/QXOM3l)

2021-05-25 11:42 UTC, costasovo approved these changes

2021-05-31 09:08 UTC, veljkho requested changes
The point 3. of the specs is not present.
As I see, it should represent a message if you send a newsletter with unsupported block type but different message to show instead "Skipped unsupported block type: { block_type }". Right now, its just an emptiness present, no message.

2021-06-01 08:02 UTC, veljkho approved these changes

2021-06-01 08:02 UTC, merged