Refactor LinkTokens to Doctrine [MAILPOET-3269]
mailpoet/mailpoet pull request #3540
Opened 2021-05-31 18:09 UTC by lysyjan

[MAILPOET-3269]

2021-06-01 13:59 UTC, pavel-mailpoet approved these changes
Good Job 👏

2021-06-07 11:40 UTC, veljkho requested changes
Can't access newsletter statistics page, any statistics page of any newsletter (simple, post notification, welcome emails..)

[Screenshot of issue](https://d.pr/i/CKFq0Z).

With disabled premium plugin I was able to open it, should be some conflict with subscriber's statistics.

2021-06-07 14:38 UTC, lysyjan commented
@veljkho Nice catch! Thanks. I have created a new PR for the premium plugin. You can verify both after the review in the premium plugin.

2021-06-14 08:12 UTC, veljkho approved these changes

2021-06-14 08:12 UTC, merged