Combining segments to create new segment [MAILPOET-3469]
mailpoet/mailpoet pull request #3561
Opened 2021-06-10 11:58 UTC by lysyjan

[MAILPOET-3469]

2021-06-11 11:22 UTC, costasovo requested changes
This is a huge amount of work! Good job! I added a couple of questions and potential issues.

2021-06-11 13:16 UTC, lysyjan commented on tests/acceptance/Segments/ManageSegmentsCest.php
> +    $i->wait(1);
Unfortunately, this wait is required. I will let a comment here.

2021-06-11 13:28 UTC, lysyjan commented on tests/acceptance/Segments/ManageSegmentsCest.php
> +    $i->wait(1);
This wait makes the test more stable. I will let a comment here.

2021-06-11 13:39 UTC, lysyjan commented on lib/Segments/DynamicSegments/Filters/UserRole.php
> +  const TYPE = 'wordpressRole';
This is not a type constant but an action constant. In DynamicSegmentFilterData are the type constants only. So I think that this filter is the right place for it.

2021-06-11 19:54 UTC, NeosinneR commented on assets/js/src/segments/dynamic/form.tsx
> +              filters.push({
It looks like this functionality is already present even before this PR; see current version at https://www.mailpoet.com/wp-admin/admin.php?page=mailpoet-segments#/new-segment. So I don't think it's necessary to fix it in this PR, but I'll make a note, and we might change it in the future.

2021-06-16 11:41 UTC, costasovo requested changes
Just one small detail.

2021-06-16 11:41 UTC, costasovo commented on lib/Entities/SegmentEntity.php
> +  public function getFiltersConnectOperand(): string {
I think the correct name should be getFiltersConnectOperator.

2021-06-17 07:02 UTC, costasovo approved these changes
Great job! 👍

2021-06-21 12:01 UTC, veljkho approved these changes

2021-06-21 12:02 UTC, merged