Dynamic segment empty name [MAILPOET-3649][MAILPOET-3559]
mailpoet/mailpoet pull request #3571
Opened 2021-06-22 15:54 UTC by lysyjan

[MAILPOET-3649]
[MAILPOET-3559]

2021-06-24 12:42 UTC, costasovo requested changes
Good job! I have just one remark.

2021-06-24 12:42 UTC, costasovo commented on assets/js/src/segments/dynamic/form.tsx
> +          ))}
I think that the APIErrorsNotice may actually display more types of errors (e.g. non unique form name) so we shouldn't display all within the form name input. I suggest moving those error notices at the very beginning of the form.

2021-06-25 13:39 UTC, costasovo approved these changes
👍

2021-06-28 09:29 UTC, veljkho approved these changes

2021-06-28 09:29 UTC, merged