Update dependencies [MAILPOET-3658]
mailpoet/mailpoet pull request #3583
Opened 2021-07-02 12:42 UTC by costasovo

[MAILPOET-3658]

After merging please notify developers on slack that in case they use `nvm` for managing node versions and they experience some errors in pre-commit hooks, they may need to create/update `~/.huskyrc` with:
```sh
# This loads nvm.sh and sets the correct PATH before running hook
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
```

2021-07-05 07:14 UTC, pavel-mailpoet approved these changes

2021-07-05 09:16 UTC, veljkho requested changes
[Fatal error](https://d.pr/i/5n0zuy) while trying to activate the plugin on qawp.net test site.
On another test site I got WordPress Error due to critical error, assuming the same issue.

2021-07-05 14:50 UTC, lysyjan approved these changes

2021-07-06 11:28 UTC, veljkho approved these changes

2021-07-06 11:29 UTC, merged