Outlook 2016 Rendering Bug in forwarded mail [MAILPOET-3468]
mailpoet/mailpoet pull request #3609
Opened 2021-08-03 10:21 UTC by lysyjan

[MAILPOET-3468]

2021-08-04 08:59 UTC, costasovo requested changes

2021-08-04 08:59 UTC, costasovo commented on lib/Config/Menu.php
> +          echo '<!--[if !mso]><!-- --><link href="https://fonts.googleapis.com/css?family=' . $fonts . '" rel="stylesheet"><!--<![endif]-->';
This code is rendered in the browser. I think we should remove the HTML condition completely from this place and and echo the link without the condition

2021-08-04 18:52 UTC, costasovo approved these changes

2021-08-16 09:44 UTC, veljkho approved these changes
Hi @lysyjan I dont have the access either. Just tested with Litmus.

2021-08-16 09:44 UTC, merged