Update php dependencies [MAILPOET-3725]
mailpoet/mailpoet pull request #3612
Opened 2021-08-05 13:48 UTC by lysyjan

[MAILPOET-3725]

2021-08-09 08:22 UTC, pavel-mailpoet approved these changes

2021-08-09 13:49 UTC, veljkho requested changes
I got fatal error while trying to activate the plugin on two different sites.

`Fatal error: Uncaught Error: Call to undefined function str_starts_with() in /home/admin/web/appium.org/public_html/wp-content/plugins/mailpoet/vendor-prefixed/nesbot/carbon/src/Carbon/Traits/Timestamp.php:2 Stack trace: #0 /home/admin/web/appium.org/public_html/wp-content/plugins/mailpoet/vendor-prefixed/nesbot/carbon/src/Carbon/Traits/Timestamp.php(2): MailPoetVendor\Carbon\Carbon::getIntegerAndDecimalParts('1628516884.0000...') #1 /home/admin/web/appium.org/public_html/wp-content/plugins/mailpoet/vendor-prefixed/nesbot/carbon/src/Carbon/Traits/Timestamp.php(2): MailPoetVendor\Carbon\Carbon::createFromTimestampUTC(1628516884) #2 /home/admin/web/appium.org/public_html/wp-content/plugins/mailpoet/lib/Doctrine/EventListeners/TimestampListener.php(20): MailPoetVendor\Carbon\Carbon::createFromTimestamp(1628516884) #3 /home/admin/web/appium.org/public_html/wp-content/plugins/mailpoet/generated/FreeCachedContainer.php(1455): MailPoet\Doctrine\EventListeners\TimestampListener->__construct(Object(MailPoet\WP\Functions)) #4 /home in /home/admin/web/appium.org/public_html/wp-content/plugins/mailpoet/vendor-prefixed/nesbot/carbon/src/Carbon/Traits/Timestamp.php on line 2`

2021-08-16 12:50 UTC, pavel-mailpoet approved these changes

2021-08-16 13:56 UTC, veljkho approved these changes

2021-08-16 13:56 UTC, merged