Refactor \MailPoet\API\JSON\v1\NewsletterLinks::get to Doctrine [MAILPOET-3626]
mailpoet/mailpoet pull request #3631
Opened 2021-08-18 08:50 UTC by pavel-mailpoet

This endpoint is used in the segments form to load all links for a newsletter. https://d.pr/i/TmWRba

[MAILPOET-3626]

2021-08-18 11:57 UTC, lysyjan submitted a review, later dismissed

2021-08-23 11:15 UTC, veljkho requested changes
Issue found.
When you make a segment with `clicked` > some newsletter > any link inside newsletter like hyperlink of some text that leads to somewhere like google.com, then save it and edit again, you'll see empty `select link` field.
SS: https://d.pr/i/7AxWOD

Issue not present on production.

2021-08-23 12:57 UTC, pavel-mailpoet commented
@costasovo The first commit was already reviewed by Jan L. So you can only review the second one.

2021-08-24 07:35 UTC, costasovo approved these changes

2021-08-25 07:22 UTC, veljkho approved these changes

2021-08-25 07:22 UTC, merged