Machine opens segment [MAILPOET-3737]
mailpoet/mailpoet pull request #3650
Opened 2021-08-31 11:22 UTC by pavel-mailpoet

[MAILPOET-3737]

2021-09-01 09:25 UTC, costasovo reviewed
I just have one question related to testing `opens.user_agent_type` for NULL value which I think is not necessary. See my comment.

2021-09-02 08:01 UTC, costasovo submitted a review, later dismissed

2021-09-06 13:03 UTC, veljkho requested changes
Everything is verified except point 4.a:
I see 0 subscribers when I make a segment with that type, but it should show definitely some higher value, because when I make segment with machine-opened within specific newsletter, I could see 3 subscribers (and it is correct, confirmed via newsletter stats).

2021-09-08 12:38 UTC, veljkho approved these changes

2021-09-08 12:38 UTC, merged