Save last subscriber's engagement [MAILPOET-3762]
mailpoet/mailpoet pull request #3655
Opened 2021-09-03 12:43 UTC by costasovo

[MAILPOET-3762]

2021-09-03 13:04 UTC, pavel-mailpoet requested changes

2021-09-03 14:06 UTC, costasovo commented on lib/Config/HooksWooCommerce.php
> +    $this->subscriberRegistration = $subscriberRegistration;
Rather set twice than never :)

2021-09-03 14:07 UTC, costasovo commented on lib/Entities/SubscriberEntity.php
> +  public function setLastEngagementAt(?DateTimeInterface $lastEngagementAt): void {
DB allows nullable, but you're right it doesn't make sense setting null in the application.

2021-09-06 07:03 UTC, costasovo commented
@pavel-mailpoet I added 3 new commits.

2021-09-06 07:09 UTC, pavel-mailpoet approved these changes

2021-09-07 08:06 UTC, veljkho approved these changes

2021-09-07 08:07 UTC, merged