Add custom validation for names in forms [MAILPOET-3786]
mailpoet/mailpoet pull request #3673
Opened 2021-09-14 09:31 UTC by lysyjan

[MAILPOET-3786]

2021-09-14 10:45 UTC, pavel-mailpoet approved these changes

2021-09-14 14:57 UTC, veljkho requested changes
I was able to enter `www.domain.com/page`... without `HTTP` protocol. Can we forbid also without a protocol?

2021-09-16 06:55 UTC, lysyjan commented
@veljkho I think that after a discussion in Jira, we can accept the current solution.

2021-09-20 07:17 UTC, veljkho approved these changes

2021-09-20 07:17 UTC, merged