Inactive subscribers improvements [MAILPOET-3774]
mailpoet/mailpoet pull request #3695
Opened 2021-09-23 09:39 UTC by lysyjan

[MAILPOET-3774]

2021-09-23 15:15 UTC, costasovo requested changes
Great job! I found an issue with COALESCE parameters, that we should address. Otherwise looks good.
Did you try some performance testing?

2021-09-23 15:15 UTC, costasovo commented on lib/Subscribers/InactiveSubscribersController.php
> +          COALESCE(s2.last_engagement_at, 0),
The same issue with COALESCE parameters as mentioned in the previous comment.

2021-09-24 07:17 UTC, lysyjan commented on lib/Subscribers/InactiveSubscribersController.php
> +          COALESCE(s.last_engagement_at, 0),
Thanks for the notification. Maybe we should improve our development environment to the strict mode in MySQL too. What do you think?

2021-09-24 07:39 UTC, costasovo commented on lib/Subscribers/InactiveSubscribersController.php
> +          COALESCE(s.last_engagement_at, 0),
@lysyjan Good idea. 👍

2021-09-24 07:40 UTC, lysyjan commented
> Did you try some performance testing?

Yes, I tried queries on the dump from mailpoet.com, and it works well on my local. I think that the run in batches assures that.

2021-09-24 09:26 UTC, costasovo approved these changes

2021-09-29 11:54 UTC, veljkho approved these changes

2021-09-29 11:54 UTC, merged