Upgrade react-select [MAILPOET-3834]
mailpoet/mailpoet pull request #3741
Opened 2021-10-19 07:09 UTC by wxa

[MAILPOET-3834]

**For QA:** 
React Select is used in settings (list selections) and dynamic segments (filters). Please make sure both single- and multi-value selects work and look good.

[MAILPOET-3834]: https://mailpoet.atlassian.net/browse/MAILPOET-3834?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2021-10-19 12:00 UTC, lysyjan submitted a review, later dismissed

2021-11-02 11:32 UTC, wxa commented
@veljkho 
> - Selecting multiple lists now makes them look with inappropriate padding [upgraded](https://d.pr/i/ILyFrV) vs [production](https://d.pr/i/c57cYP)
> - Longer newsletter titles produce overlaps in Segments selectors: [upgraded](https://d.pr/i/G29kbz) vs [production](https://d.pr/i/hyLNc7)

Fixed both.

2021-11-02 11:37 UTC, lysyjan submitted a review, later dismissed

2021-11-02 13:57 UTC, veljkho requested changes
For the first issue, the only leftover is the top/bottom padding for the whole section when adding multiple lists, please refer to this [screenshot](https://d.pr/zAhzVK). Sorry, I should have mentioned it on Slack today.

But for the second issue, I still see it for some reason: https://d.pr/i/O8XxLG

2021-11-03 18:54 UTC, wxa commented
@veljkho Fixed again.

2021-11-04 09:15 UTC, veljkho approved these changes

2021-11-04 09:15 UTC, merged