Disable re-engagement Emails if tracking is disabled [MAILPOET-3840]
mailpoet/mailpoet pull request #3752
Opened 2021-10-22 23:16 UTC by brezocordero

This PR disables re-engagement emails when tracking is disabled.
I have used some code from https://github.com/mailpoet/mailpoet/pull/3745/files, please merge that PR into master first.

To test enable the feature flag `'re-engagement-email'` and create a re-engagement email (status active).

1. On MailPoet Settings > Advanced
Select 'No' on tracking setting. 
Check that a note is displayed underneath saying that re-engagement emails are disabled.
Save the settings.
Check there is a message saying that the re-engagement emails have been disabled
2. On Emails listing
Go to emails listing, re-engagement tab.
Check the email is disabled
Try enabling it with the toggle.
Check you can not and there is a notice saying re-engagement emails are disabled.
3. On Email editor
Edit the email, click on Next.
Check the button Activate is disabled.
Check the tooltip says: `Re-engagement emails are disabled because open and click tracking is disabled.`
Click on the link on the tooltip
4. On Settings
Select yes on tracking setting.
Save the settings.
Check there is a notice saying that you need to re-activate re-engagement emails
Go to emails, click on re-engagement tab.
Edit the email, click on next.
Check that you can Activate the email.
Activate it. 
On Listings, check that you can deactivate/activate with the toggle.
Deactivate the email
6. On settings
Disable tracking
Save the settings
Check there is no notice that the emails were disabled (because there were no active re-engagement emails.)

[MAILPOET-3840]

[MAILPOET-3840]: https://mailpoet.atlassian.net/browse/MAILPOET-3840?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2021-10-27 13:34 UTC, pavel-mailpoet submitted a review, later dismissed

2021-11-01 15:06 UTC, veljkho requested changes
Good job!
I have found one issue but that was not part of the specs.
It is about warning message that user is getting after trying to activate re-engagement email but when open & tracking is disabled: https://d.pr/i/UN13AN
There's no link inside a warning message for **open and click tracking**.

That might be forgotten during specifications.

2021-11-01 17:53 UTC, brezocordero commented
> Good job! I have found one issue but that was not part of the specs. 

@veljkho Thanks! Modified following the updated specs.

2021-11-02 08:11 UTC, veljkho approved these changes

2021-11-02 08:12 UTC, merged