Add info when form is inactive to subscription form block [MAILPOET-3896]
mailpoet/mailpoet pull request #3783
Opened 2021-11-04 13:19 UTC by lysyjan

[MAILPOET-3896]

2021-11-05 12:25 UTC, costasovo submitted a review, later dismissed

2021-11-08 09:31 UTC, veljkho requested changes
Hey Jan,
I see that you've fixed issue but for MailPoet Subscription Form block and not MailPoet 3 Form block that I was referring. Is it fixable also for [MailPoet 3 Form block](https://d.pr/i/PEcRT8)? Is it part of our development? Otherwise, this is fixed for MailPoet Subscription Form block.

2021-11-17 10:08 UTC, costasovo approved these changes

2021-11-17 14:39 UTC, veljkho approved these changes

2021-11-17 14:39 UTC, merged