Remove re-engagement-email feature flag [MAILPOET-3859]
mailpoet/mailpoet pull request #3814
Opened 2021-11-18 15:29 UTC by rodrigoprimo

@costasovo, before reviewing this PR, please check the comment that I left on the Jira ticket.

[MAILPOET-3859]

2021-11-23 08:51 UTC, costasovo requested changes
Good job! I've added code comment!

Thanks for the heads up about the link to re-engagement page. I was able to replicate the same problem and it seems to me that there is some functionality missing. I'll share more details in [the Jira ticket](https://mailpoet.atlassian.net/browse/MAILPOET-3859).

2021-11-23 08:51 UTC, costasovo commented on lib/Cron/Daemon.php
> -    if ($this->featureSwitch->isSupported(FeaturesController::RE_ENGAGEMENT_EMAIL)) {
I think that this was the only usage of `$this->featureSwitch` within the class. Could you please also remove the dependency from the constructor?

2021-11-24 14:12 UTC, rodrigoprimo commented
Good catch, @costasovo. I pushed a new commit removing this property. I will ask for another review once I finish implementing the code to parse the new shortcode in a separate PR.

2021-11-25 13:00 UTC, rodrigoprimo commented
Since #3822 was approved, this PR is not ready for a final review.

2021-11-26 08:54 UTC, costasovo submitted a review, later dismissed
👍

2021-11-29 09:32 UTC, veljkho requested changes
Everything's good except one thing:

When clicking the button in the email **[Yes, keep me subscribed!](https://d.pr/i/3TU4um)**, I see [404 page error](https://d.pr/i/xH48rr). This is because the button link is:

https: //domain-name.com/?mailpoet_router&endpoint=track&action=click&data=WzE1MzksImJmNzhhNjM1OTBlN2QwZDQwZDcxNmFmNjIxODVkNzUyIiwiMjgxOSIsIjE1MjVkMDk1ZDE4NyIsZmFsc2Vd

and where I landed is:

https: //domain-name.com/[link:subscription_re_engage_url]

Looks like we have shortcode in the URL. I tested the page in Settings > Basics.. where [it worked](https://d.pr/i/LdG9pv).

2021-11-29 10:16 UTC, costasovo commented
> When clicking the button in the email Yes, keep me subscribed!, I see 404 page error. 

@veljkho The issue happened because the shortcode processing was missing. We added it in [a separate PR](https://github.com/mailpoet/mailpoet/pull/3822). It was already merged so I've rebased this branch and the link should now work as expected. Can you please test it again?

2021-11-29 15:23 UTC, veljkho approved these changes
Thanks for letting me know @costasovo , this was the case. Feature is working as expected!

2021-11-29 15:23 UTC, merged

2021-11-30 13:07 UTC, rodrigoprimo commented
Thanks for stepping in and rebasing the branch, @costasovo!