Allow multiple values in "purchased this product" segment [MAILPOET-3954]
mailpoet/mailpoet pull request #3824
Opened 2021-11-26 16:20 UTC by lysyjan

[MAILPOET-3954]

2021-11-29 09:18 UTC, costasovo approved these changes
Great job!

2021-11-29 13:53 UTC, veljkho requested changes
1. The specs say: a) Change the name to `purchased product` but instead it is now `purchased products`.

2. The specs say: e) Make sure the existing segments with a single value continue working
This is not the case now, I've lost all subscribers who have bought a product, I had this segment before this change and it had 6 subscribers.. now says 0 subscribers for that segment.

2021-11-29 16:27 UTC, lysyjan commented
1. It is fixed. Thanks!
2. When you run migrations, it should be solved.

2021-11-30 12:14 UTC, costasovo requested changes
We need to update the version check in data migration.

2021-11-30 12:14 UTC, costasovo commented on lib/Config/Migrator.php
> +    if (version_compare($this->settings->get('db_version', '3.74.2'), '3.74.1', '>')) {
We released 3.74.2 so we need to update the migration check.

2021-12-01 07:45 UTC, costasovo approved these changes

2021-12-01 08:13 UTC, veljkho approved these changes

2021-12-01 08:13 UTC, merged