Add more comparison options to three different segments [MAILPOET-3614]
mailpoet/mailpoet pull request #3855
Opened 2021-12-09 19:57 UTC by rodrigoprimo

Noting that it won't be possible to test the changes to the "# of machine-opens" segment until #3853 is merged. #3853 fixes a bug in this segment that is preventing it from working properly.

[MAILPOET-3614]

2021-12-10 08:59 UTC, pavel-mailpoet submitted a review, later dismissed

2021-12-22 15:01 UTC, rohankacharegs commented
GlobalStep Verified

2021-12-23 08:16 UTC, veljkho requested changes
I found an issue:
The machine-opened calculation does not work. I compared it with the production build where it worked for `more than` and `less than`, but now with this build, they don't work along with the new options `equals`, `not equals`.
[Here is the proof](https://d.pr/i/zRGHDM) that I have at least one subscriber with `machine-opened` data.

2022-01-11 17:57 UTC, rodrigoprimo commented
@veljkho, maybe this is related to the bug fixed on #3853 that I mentioned in the description of this PR? Or are you talking about a different problem? Now that #3853 has been merged, I have rebased mater into this branch. Could you please test again?

2022-01-12 14:41 UTC, veljkho commented
@rodrigoprimo now it works as expected, thanks! Will merge this after we resolve the issue with the current release build problems.

2022-01-13 08:22 UTC, veljkho approved these changes

2022-01-13 08:22 UTC, merged