Update WP.org description [MAILPOET-4167]
mailpoet/mailpoet pull request #3992
Opened 2022-02-28 16:59 UTC by NeosinneR

[MAILPOET-4167]

2022-02-28 17:28 UTC, brezocordero requested changes

2022-02-28 17:28 UTC, brezocordero commented on mailpoet/readme.txt
> +* Advanced functionality available to help achieve growth
Nitpicking: The other lists have a period on the last item.

2022-02-28 17:57 UTC, brezocordero approved these changes

2022-03-01 07:51 UTC, veljkho approved these changes

2022-03-01 07:51 UTC, merged