Exclude orders not payed and on hold from calculating purchase segments [MAILPOET-4127]
mailpoet/mailpoet pull request #4007
Opened 2022-03-11 10:43 UTC by websupporter

Fixes [MAILPOET-4127]

To test:

1. Create Pending payment and On-hold orders.
2. Create a “Purchased this product” segment with this product
3. Customers should not appear in the segment
4. Create a “Purchased in category” segment with this product
5. Customers should not appear in the segment

2022-03-11 23:01 UTC, brezocordero requested changes
@websupporter Code looks good and it works but there are other 3 segments where we also need to apply the changes:

- WooCommerceCountry.php
- WooCommerceProduct.php
- WooCommerceTotalSpent.php

If it gets too big, please create separate tickets and I will approve this PR.

2022-03-14 09:29 UTC, websupporter commented
Hi @brezocordero, thanks for looking into the PR

WooCommerce category is part of this PR or did I miss something?
For the other segments, I have created separate Jira issues, as I think the definition of what counts as an order will probably vary in those cases: [MAILPOET-4188], [MAILPOET-4187]

2022-03-14 15:41 UTC, brezocordero approved these changes
LGTM! 
Thanks for creating the other tickets.

2022-03-24 14:29 UTC, rohankacharegs commented
GlobalStep Verified

2022-03-24 15:00 UTC, veljkho approved these changes

2022-03-24 15:00 UTC, merged