Improve message for confirmation emails [MAILPOET-4149]
mailpoet/mailpoet pull request #4097
Opened 2022-04-25 14:55 UTC by costasovo

[MAILPOET-4149]

[MAILPOET-4149]: https://mailpoet.atlassian.net/browse/MAILPOET-4149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Testing instructions:
1. Use a third-party sending method in `MailPoet` > `Settings` > `Send With…` (can be Your Host)
2. Disable signup confirmation in `MailPoet` > `Settings` > `Sign-up Confirmation`
3. Go to Subscribers page and try to `resend email confirmation` for any `Unconfirmed` subscriber (in case you don't have, edit one and set it to be unconfirmed status)
4. Verify that you see the error message correctly, test the link inside the sentence and make sure it leads to the settings page
Note: Additionally, enable the Sign-up Confirmation in the settings and try to resent the confirmation, make sure you have received it and click the link in email to confirm the subscription. Make sure the subscriber is subscribed again.

2022-04-25 21:43 UTC, rodrigoprimo approved these changes
Good job! The changes look good to me.

The only thing that I noticed that is not directly related to this ticket is that if the top of the page is not visible because the user scrolled down a bit, the error message is not visible when they click on the link to resend the confirmation email. I think this can be confusing as the users might miss that there was an error when sending the confirmation email. They don't get any visible feedback that there was a problem when they clicked the link.

What do you think? If you agree, maybe we should create a new ticket?

2022-04-26 07:26 UTC, costasovo commented
> The only thing that I noticed that is not directly related to this ticket is that if the top of the page is not visible because the user scrolled down a bit, the error message is not visible when they click on the link to resend the confirmation email. I think this can be confusing as the users might miss that there was an error when sending the confirmation email. They don't get any visible feedback that there was a problem when they clicked the link.

Aha! Good catch. I haven't realized that. This seems to be a general problem with our notices.

> What do you think? If you agree, maybe we should create a new ticket?

I think it is a UX problem that may cause confusion. Do you have some suggestions on how to solve the issue? I can think about scrolling up when a notice appears or making the notice sticky.

2022-04-26 17:20 UTC, rodrigoprimo commented
> I think it is a UX problem that may cause confusion. Do you have some suggestions on how to solve the issue? I can think about scrolling up when a notice appears or making the notice sticky.

@costasovo, I also thought about scrolling up when a notice appears. Just making the notice stay on the page instead of disappearing after some time is not enough in my opinion. That being said, maybe we can get input from a designer on this? I'm not sure what is the best way to handle UX problems in MailPoet.

2022-04-27 07:03 UTC, costasovo commented
> @costasovo, I also thought about scrolling up when a notice appears. Just making the notice stay on the page instead of disappearing after some time is not enough in my opinion. 

@rodrigoprimo I've checked how it works in WP core listings (users and posts) and clicking on item actions in those pages triggers a page reload and after the reload the page is scrolled to the top and notice is visible. So Scrolling up seems to be a good option how to make the behavior consistent with WP.

> That being said, maybe we can get input from a designer on this? I'm not sure what is the best way to handle UX problems in MailPoet.

Well in the past we usually asked @NeosinneR or discussed it in the product channel. In this case, we probably don't need input from a designer because the scrolling options seem to be reasonable. But I would like to learn where we should ask or how to get input from a designer in case we needed it. Do you know where to ask?

2022-04-27 13:58 UTC, rodrigoprimo commented
> So Scrolling up seems to be a good option how to make the behavior consistent with WP.

:+1: 

> Do you know where to ask?

Unforutantely I don't know what is the process for MailPoet.

2022-04-27 14:06 UTC, NeosinneR commented
I don't think there is any official process for requesting a design opinion on little things like this for MailPoet, so as Rosta mentioned, you can ask in #mailpoet-product or me directly and I can try to help. WooDesign, however, aims to have a dedicated designer for MailPoet in the medium-term and there is a chance, that Mikalai, which was hired for the Automation project might take this role once he is onboarded and Automation is progressing.

2022-05-02 09:42 UTC, rohankacharegs commented
GlobalStep Verified

2022-05-02 10:54 UTC, veljkho commented
We have issue with the wording,
Currently: Please enable it to resend confirmation emails or update your subscriber’s `statuz manuoually`.
Expected: Please enable it to resend confirmation emails or update your subscriber’s `status manually.`

2022-05-02 10:55 UTC, veljkho requested changes
We have issue with the wording,
Currently: Please enable it to resend confirmation emails or update your subscriber’s `statuz manuoually`.
Expected: Please enable it to resend confirmation emails or update your subscriber’s `status manually`.

2022-05-02 11:47 UTC, veljkho approved these changes
Verified

2022-05-02 11:47 UTC, merged