Mailpoet 4341 creating custom field from form breaks form editor
mailpoet/mailpoet pull request #4132
Opened 2022-05-13 15:34 UTC by samnajian

2022-05-17 07:47 UTC, lysyjan requested changes
I tried your fix, and I have found [an issue](https://d.pr/v/FkyOy0). A deleted custom field stays in the list of blocks.

2022-05-24 09:49 UTC, veljkho approved these changes

2022-06-06 08:34 UTC, rohankacharegs commented
GlobalStep Verified

2022-06-06 09:11 UTC, veljkho approved these changes

2022-06-06 09:11 UTC, merged