Verify that new email is unique when editing a subscriber
mailpoet/mailpoet pull request #4150
Opened 2022-05-21 02:53 UTC by brezocordero

With this PR, it throws an exception and displays a friendlier message if the new email already exists.

To test:
- Go to MailPoet>Subscribers>Edit a subscriber
- Enter an email that already exists and click save
- Check you see the message: `A subscriber with E-mail '{$email}' already exists.` instead of the DB exception

When working on this issue I found a tiny bug and fixed it:
To test:
- Go to MailPoet>Subscribers>Import>Proceed>Paste data
- Enter data for 1 subscriber `mary@jane.com, mary, jane` (doesn't really matter) click next.
- Check that instead of seeing `An unknown error has occurred` you see `Another record already exists. Please specify a different "name".`

[MAILPOET-4259]

2022-05-23 16:07 UTC, johnolek requested changes
Looks good overall! The only change I would definitely like to see is to ensure that we're still trying to log errors if an unknown exception occurs during a save (more details in my comment).

2022-05-23 16:13 UTC, johnolek commented
@brezocordero I'm not sure I'm understanding how to reproduce this issue you describe:

> When working on this issue I found a tiny bug and fixed it:
> To test:
> 
> Go to MailPoet>Subscribers>Import>Proceed>Paste data
> Enter data for 1 subscriber mary@jane.com, mary, jane (doesn't really matter) click next.
> Check that instead of seeing An unknown error has occurred you see Another record already exists. Please specify a different "name"

When I paste an email for an existing subscriber and click next, I don't see an error at all. Then on the import step, if I choose `No` for `Update existing subscribers’ information, like first name, last name, etc` and click `Import`, it just tells me that `No subscribers were added or updated.` Is there something I could be missing?

2022-05-23 20:00 UTC, brezocordero commented
> I'm not sure I'm understanding how to reproduce this issue you describe:

So sorry @johnolek, I forgot a step in the test! I have updated the issue.

2022-05-24 15:38 UTC, brezocordero commented on mailpoet/lib/API/JSON/v1/Subscribers.php
> +      ]);
Removed the last catch block so that the message gets logged.

2022-05-24 20:48 UTC, johnolek approved these changes
Thanks for making those changes and updating the testing instructions -- this looks good to me!

2022-06-06 09:36 UTC, veljkho approved these changes

2022-06-06 09:58 UTC, rohankacharegs commented
GlobalStep Verified

2022-06-06 09:59 UTC, merged