Made checkboxes in a form accessible according to the WCAG-standards …
mailpoet/mailpoet pull request #4204
Opened 2022-06-21 13:05 UTC by simsekb

…by adding a fieldset around them and adding a legend describing the fieldset's purpose (name).

2022-06-29 12:39 UTC, simsekb commented
I accidently commited another change into this branch..

2022-07-11 13:42 UTC, costasovo requested changes
Thank you for your contribution! I'm sorry it took me so long to get to this!

The change makes sense. The thing is that adding wrapping those checkboxes into a fieldset would change the appearance forms which already exist on user sites.

Here is an example:

**1) Form before the change**
<img width="605" alt="Screenshot 2022-07-11 at 15 21 07" src="https://user-images.githubusercontent.com/1082140/178275395-4d39f355-dfd7-46d4-8eca-fefbed199bbf.png">

**2) After switching to this branch**
<img width="613" alt="Screenshot 2022-07-11 at 15 21 17" src="https://user-images.githubusercontent.com/1082140/178275343-fa3ec580-631a-47d6-9082-e83c8574d5b2.png">

I think we could work around this by adding some CSS reset for the fieldset element inside mailpoet forms. The reset could be added into [a file with CSS rules used for the forms on the frontend](https://github.com/mailpoet/mailpoet/blob/7e59ad7f9061f2b9df285d2745ba858168661b57/mailpoet/assets/css/src/components-public/_public.scss).

Could you please add the CSS rules to ensure we don't change the appearance?

As for the second change, I'm not sure I fully understand the reason. Could you please explain a bit what was the problem?

2022-07-11 22:38 UTC, simsekb commented
> Thank you for your contribution! I'm sorry it took me so long to get to this!
> 
> The change makes sense. The thing is that adding wrapping those checkboxes into a fieldset would change the appearance forms which already exist on user sites.
> 
> Here is an example:
> 
> **1) Form before the change** <img alt="Screenshot 2022-07-11 at 15 21 07" width="605" src="https://user-images.githubusercontent.com/1082140/178275395-4d39f355-dfd7-46d4-8eca-fefbed199bbf.png">
> 
> **2) After switching to this branch** <img alt="Screenshot 2022-07-11 at 15 21 17" width="613" src="https://user-images.githubusercontent.com/1082140/178275343-fa3ec580-631a-47d6-9082-e83c8574d5b2.png">
> 
> I think we could work around this by adding some CSS reset for the fieldset element inside mailpoet forms. The reset could be added into [a file with CSS rules used for the forms on the frontend](https://github.com/mailpoet/mailpoet/blob/7e59ad7f9061f2b9df285d2745ba858168661b57/mailpoet/assets/css/src/components-public/_public.scss).
> 
> Could you please add the CSS rules to ensure we don't change the appearance?
> 
> As for the second change, I'm not sure I fully understand the reason. Could you please explain a bit what was the problem?

Ah alright, I thought I had that covered too, maybe our own MP-addon already had that one fix it. I'll commit a change for that one tommorow morning around 9-10 AM. As for the second change; when filling in an email field, there should be two errors. The one when the email is filled in incorrectly (is in a valid email format: 'type-message') and when the email field is not empty ('required-message'). When looking at the current situation, the 'error-message' overrules both situations and always shows the message: "Please specify a valid email address".

2022-07-12 14:23 UTC, costasovo reviewed
Thanks for your quick reaction! I think it might be better to restrict the fieldset CSS reset so that it is applied only for the MailPoet forms.

2022-07-12 14:23 UTC, costasovo commented on mailpoet/assets/css/src/components-public/_public.scss
> +fieldset {
This will change the global fieldset and possibly may influence other fieldsets on a site. Wouldn't it be better to restrict it only for fieldset inside `.mailpoet_form`? This way the rule will have also bigger specificity so lower not get overridden by a theme.

2022-07-12 14:30 UTC, simsekb commented on mailpoet/assets/css/src/components-public/_public.scss
> +fieldset {
You're absolutely right! I'm committing the change now.

2022-07-12 14:53 UTC, costasovo approved these changes
Thank you @simsekb! The PR looks good to me! We still haven't solved the issue with the public builds so I'll recreate the PR under my user (maybe also merge some commits). Same as I did with the previous PR.

Just want to let you know I'll get to this the next Monday. Thanks again for your contribution and your patience!

2022-07-12 15:10 UTC, simsekb commented
> Thank you @simsekb! The PR looks good to me! We still haven't solved the issue with the public builds so I'll recreate the PR under my user (maybe also merge some commits). Same as I did with the previous PR.
> 
> Just want to let you know I'll get to this the next Monday. Thanks again for your contribution and your patience!

Awesome! When do you think these changes would go into production?

2022-07-14 05:39 UTC, simsekb commented
> Thank you @simsekb! The PR looks good to me! We still haven't solved the issue with the public builds so I'll recreate the PR under my user (maybe also merge some commits). Same as I did with the previous PR.
> 
> Just want to let you know I'll get to this the next Monday. Thanks again for your contribution and your patience!

Awesome! When do you think these changes would go into production? @costasovo

2022-07-19 09:45 UTC, costasovo commented
@simsekb I'm closing this PR in favor of a new PR I've created: https://github.com/mailpoet/mailpoet/pull/4256. 
I also added a couple of additional commits for issues detected by tests on CI and a few things (e.g. it also affects manage subscription forms, legend input needs escaping) I missed in the original review.

2022-07-19 09:45 UTC, closed without merging

2022-08-09 11:00 UTC, alex-mailpoet commented
@simsekb This change was released today in MailPoet 3.94.0.