Display tags on the subscribers listing page [MAILPOET-4441]
mailpoet/mailpoet pull request #4222
Opened 2022-07-04 12:23 UTC by lysyjan

This pull request is the second in a row for the tags feature. The review should start from [this commit.](https://github.com/mailpoet/mailpoet/commit/584e225f95df0617916e7a57c4c9801a62f4498d)

For QA: This PR has to merge after [the first one](https://github.com/mailpoet/mailpoet/pull/4214) and should be rebased.

2022-07-07 13:49 UTC, triple0t reviewed
Looks good.
Just some comments.

Kindly locate below

2022-07-07 13:49 UTC, triple0t commented on mailpoet/assets/js/src/common/tag/_stories/tags.tsx
> +const strings = ['One', 'Two', 'Third tag'];
Was this is intentional?

Why not 'First', 'Second', 'Third'? 
or
'One', 'Two', 'Three'?

2022-07-07 13:49 UTC, triple0t commented on mailpoet/assets/js/src/common/tag/tags.tsx
> +            variant={variant === undefined ? 'list' : variant} // due to backward compatibility we use `list` as the default value
Hmmm
A question here, why are we specifically checking for `undefined`?

if we need to account for backward compatibility
why not
```
variant={variant ? variant : 'list' }
```

This would check for both undefined, null, and other falsely values

2022-07-07 13:49 UTC, triple0t commented on mailpoet/assets/js/src/subscribers/list.jsx
> +    if (subscriber.tags.length > 0) {
Note here

I couldn’t locate the initial value for `subscriber.tags`.
Are we sure it would allow be an Array? even if it's an empty array `[]`?

An alternative would be checking for the presence of `subscriber.tags` and then `subscriber.tags.length > 0`

e.g.
```
if (subscriber.tags && subscriber.tags.length > 0) {
```

2022-07-07 13:55 UTC, lysyjan commented on mailpoet/assets/js/src/common/tag/_stories/tags.tsx
> +const strings = ['One', 'Two', 'Third tag'];
I want a tag that contains a space in the name.

2022-07-07 13:56 UTC, lysyjan commented on mailpoet/assets/js/src/common/tag/tags.tsx
> +            variant={variant === undefined ? 'list' : variant} // due to backward compatibility we use `list` as the default value
That will work too. I will change it. Thank you

2022-07-07 14:02 UTC, triple0t commented on mailpoet/assets/js/src/common/tag/_stories/tags.tsx
> +const strings = ['One', 'Two', 'Third tag'];
Noted.
In that case, can we use: 'First', 'Second', 'Third tag'?


<img width="318" alt="Screenshot 2022-07-07 at 3 00 28 PM" src="https://user-images.githubusercontent.com/30554163/177792379-aed5f550-aba7-4fd0-b8d1-8d7fb7fba93c.png">

2022-07-07 14:05 UTC, lysyjan commented on mailpoet/assets/js/src/subscribers/list.jsx
> +    if (subscriber.tags.length > 0) {
The initial value gets from the Subscribers::listing endpoint, and I added tags in [this commit](https://github.com/mailpoet/mailpoet/pull/4222/commits/584e225f95df0617916e7a57c4c9801a62f4498d). As you can see tags are always an array.

2022-07-07 14:05 UTC, lysyjan commented on mailpoet/assets/js/src/common/tag/_stories/tags.tsx
> +const strings = ['One', 'Two', 'Third tag'];
Sure, no problem.

2022-07-07 14:07 UTC, triple0t commented on mailpoet/assets/js/src/subscribers/list.jsx
> +    if (subscriber.tags.length > 0) {
Noted.
Thank you for highlighting that.

2022-07-07 15:47 UTC, lysyjan commented
@triple0t I have addressed both fixes in [the last commit](https://github.com/mailpoet/mailpoet/pull/4222/commits/eb979caf1d2e930759d89f204ab3eab2ddb5a25b). It's a fixup commit because I assume that this branch will be rebased.

2022-07-07 16:18 UTC, triple0t submitted a review, later dismissed
LGTM 🎉

2022-07-12 11:35 UTC, veljkho commented
Hi @lysyjan 
I see some conflicting files.. probably after merging the 1st PR.

2022-07-12 11:38 UTC, lysyjan commented
@veljkho This was a little bit expected.  I am going to rebase it.

2022-07-12 12:30 UTC, veljkho requested changes
Everything's fine, good job!
I have a suggestion to [make those tags smaller](https://d.pr/i/6n1BQ5).. they are currently so big to me, looking even bigger than list badges.. Also, tags are less important than lists, so I would make them smaller in size here in the listing. What do you think @lysyjan CC @NeosinneR

2022-07-12 12:40 UTC, lysyjan commented
@veljkho Thanks for pointing this out. I can use the same size as is in the score column. Do you agree with me @pavel-mailpoet?

2022-07-12 12:45 UTC, pavel-mailpoet commented
@lysyjan Sure, let's experiment with them. I have no preference. We can change them now or later if we want. Also, the colour will be probably different in the future (user editable)

2022-07-14 06:14 UTC, triple0t approved these changes

2022-07-14 08:37 UTC, veljkho approved these changes

2022-07-14 08:37 UTC, merged