Improve the DMARC error message - MAILPOET-4311
mailpoet/mailpoet pull request #4319
Opened 2022-08-16 08:54 UTC by triple0t

When the DMARC error message is displayed, add the sentence "Click here to start the authentication". This will be a link that opens the verify domain dialogue

MAILPOET-4311

Testing:
* Clear your errors and make sure you don't have any sending error
* Create a new newsletter. You may use any of the demo contents
* On the newsletter sending page, use an email domain with restricted DMARC policy e.g @automattic.com (You might have to authenticate the email address)
* Fill in the other fields and send the email. (I would recommend the use of a sending list with few subscribers e.g 1 or 2 subscribers)
* Wait a few minutes for the error message 
* Click on the "Click here to start the authentication" link
* Notice the sender domain verification modal.

2022-08-31 16:54 UTC, samnajian requested changes
Works nicely, but a few short comments.

2022-08-31 16:54 UTC, samnajian commented on mailpoet/assets/js/src/listing/notices.jsx
> +      return { ...acc };
No need to create another object here, I guess you can simply return `acc`, what do you think?

2022-08-31 16:54 UTC, samnajian commented on mailpoet/assets/js/src/listing/notices.jsx
> +        {...otherAttributes}
I feel like using `allowedAttributeNames` instead of `allowedAttributesList` and using `allowedAttributes` instead of `otherAttributes` would be a little easier to read understand what each variable holds, but it's just a suggestion!

2022-09-01 08:10 UTC, samnajian approved these changes
LGTM! thanks :)

2022-09-08 10:51 UTC, veljkho approved these changes

2022-09-08 10:51 UTC, merged