Fix subscribers' segment filter [MAILPOET-4563]
mailpoet/mailpoet pull request #4321
Opened 2022-08-16 14:07 UTC by lysyjan

[MAILPOET-4563]

2022-08-17 12:15 UTC, triple0t requested changes
Thanks for the PR @lysyjan 

I do not believe this PR solves the issues highlighted in the ticket description.
i.e Item 4: `Now try to filter all trashed subscribers by the list (the one you know they are related to)`

e.g
Here is my Trashed list 

Trying to filter trashed subscribers via list
<img width="1599" alt="Screenshot 2022-08-17 at 1 04 45 PM" src="https://user-images.githubusercontent.com/30554163/185114903-59a37264-0ed5-44a9-a8f8-8fa70b7cee48.png">
**Notice** the subscribers' list does not show up in the dropdown

Here is the full trashed list
![mp3 localhost_wp-admin_admin php_page=mailpoet-subscribers](https://user-images.githubusercontent.com/30554163/185115227-e326892a-0361-4981-a3e4-881f83d1c55d.png)


Can you please take another look?

2022-08-19 17:34 UTC, lysyjan commented
@triple0t You forgot to assign this PR back to me, and I overlooked your comment.
Unfortunately, this behavior depends on the segments cache. If you use the recalculate button, it should be okay.

2022-08-29 20:56 UTC, triple0t submitted a review, later dismissed
I can confirm clicking the "Recalculated now" button updates the list selector.

2022-08-31 13:51 UTC, veljkho approved these changes

2022-08-31 13:52 UTC, merged