Improve error messages on the last step of sending [MAILPOET-4506]
mailpoet/mailpoet pull request #4345
Opened 2022-09-05 08:45 UTC by lysyjan

I decided to use a slightly different approach for validation segments compared to the ticket specification.
The error message is displayed under the select instead of a tooltip on the sending button.

[MAILPOET-4506]

2022-09-07 15:44 UTC, johnolek requested changes

2022-09-07 15:44 UTC, johnolek commented on mailpoet/assets/js/src/parsley-validators.jsx
> +      });
This will make the form appear invalid if you've selected any segments with 0 subscribers, including if you've selected other segments that do have subscribers, which isn't the intended behavior (I double checked with @NeosinneR). It should be valid/possible to send as long as there's 1 list selected that has subscribers.

2022-09-07 19:36 UTC, NeosinneR commented
![image](https://user-images.githubusercontent.com/470616/188961099-6d4495b3-6475-41ae-87b9-56dcc72bc823.png)

@lysyjan the change (from tooltip to error message) is okay, but seeing it in action, I see a couple of other UX issues.

1. The two error messages (list and email) look slightly different. Could you please unify them, with the authorized error being the correct one?
2. The green success state is really confusing. It is only shown on some of the inputs, and it's even shown on the input with an error message (I understand why, but the UX is subpar). Could you please completely remove parsley's success styling?
3. The authorized email error was designed to be on one line. There is definitely room, but it seems the holder for the error is not as wide as the input. Could you please make it 100% wide so the message fits on one line?

Let me know your thoughts, and I can also update the specs later.

2022-09-08 08:58 UTC, lysyjan commented
@NeosinneR Thank you for your notes. It makes sense to me, so I will improve the behavior. Please change the ticket description for easier validation by Veljko.

2022-09-08 16:53 UTC, johnolek submitted a review, later dismissed
LGTM!

2022-09-14 12:50 UTC, Aschepikov requested changes
Hi. During the testing I found some issues:
**1. In the ticket margin-top: 6px; and in the pr and on the site it is 2**

![image](https://user-images.githubusercontent.com/113185437/190156888-140b5dd5-98dd-4df5-9e1b-ab61562b16bf.png)
![image](https://user-images.githubusercontent.com/113185437/190156968-5909b943-ab05-4457-9551-0754918a77b8.png)


**2. The error message "Please select a list with subscribers" should contain a dot at the end.** 

![image](https://user-images.githubusercontent.com/113185437/190157410-c91fb6fa-b671-4091-b276-35637d00c08e.png)
![image](https://user-images.githubusercontent.com/113185437/190157583-65a4f764-e3c6-4370-b69b-4a8e07b7721c.png)

2022-09-14 16:25 UTC, lysyjan commented
@Aschepikov Thank you for your feedback!
1. This is intentional because it didn't look fine in some cases when I used `6px`. See an example below: 
![image](https://d.pr/i/aEdo24+)
What do you think about that @NeosinneR?
2. I fixed it.

2022-09-14 18:50 UTC, NeosinneR commented
@lysyjan right, I wasn't counting on errors on inputs with the small space, only with the larger space below them. If it looks good with 2px, that's fine by me.

2022-09-15 07:35 UTC, Aschepikov approved these changes
This is verified, good job.

2022-09-15 07:35 UTC, merged