Remove the version number from the plugin name [MAILPOET-4474]
mailpoet/mailpoet pull request #4350
Opened 2022-09-07 11:35 UTC by pavel-mailpoet

[MAILPOET-4474]

2022-09-07 16:01 UTC, johnolek requested changes
@pavel-mailpoet This all looks good to me! I noticed we still have a few references to MailPoet 3 in the public API docs (https://github.com/mailpoet/mailpoet/tree/remove-3/doc#mailpoet-3---documentation-for-integrators).

<img width="920" alt="image" src="https://user-images.githubusercontent.com/8656640/188925353-6c665dd2-6d62-49f3-a756-13a209bb350a.png">

Should those also be updated as part of this PR?

2022-09-08 07:08 UTC, pavel-mailpoet commented
@johnolek Thank you for looking at it. I was only looking inside the mailpoet folder and missed this. I will update the docs as well.

2022-09-08 16:27 UTC, johnolek approved these changes

2022-09-09 09:25 UTC, veljkho approved these changes

2022-09-09 09:25 UTC, merged