Fix creation notification history records
mailpoet/mailpoet pull request #4385
Opened 2022-09-23 13:15 UTC by lysyjan

## Description

_N/A_

## Code review notes

_N/A_

## QA notes

_N/A_

## Linked PRs

_N/A_

## Linked tickets

_N/A_

## After-merge notes

_N/A_

2022-09-23 13:21 UTC, costasovo requested changes
Looks good. I have just one suggestion.

2022-09-23 13:21 UTC, costasovo commented on mailpoet/lib/Cron/Workers/Scheduler.php
> +        'creating post notification failed',
I think 'creating post notification failed' should be 'creating post notification history failed'.

2022-09-26 08:39 UTC, costasovo approved these changes
LGTM! 👍

2022-09-26 11:23 UTC, Aschepikov approved these changes
Good job!

2022-09-26 11:23 UTC, merged