Add new Subscriber hooks [MAILPOET-4727]
mailpoet/mailpoet pull request #4443
Opened 2022-10-20 18:39 UTC by lysyjan

## Description

This PR adds new hooks for better integration with other plugins. Here is a list:
- `mailpoet_subscriber_created(int $subscriberId)`
- `mailpoet_subscriber_updated(int $subscriberId)`
- `mailpoet_subscriber_deleted(int $subscriberId)`
- `mailpoet_multiple_subscribers_created(int $minCreatedAtTimestamp)`
- `mailpoet_multiple_subscribers_updated(int $minUpdatedAtTimestamp)`
- `mailpoet_multiple_subscribers_deleted(array $subscriberIds)`

## Code review notes

A new layer was created that contains stored changes from a repository and a listener, which are fired in the WP `shutdown` hook. The new layer should prevent multiple calls of update hooks. 

## QA notes

_N/A_

## Linked PRs

_N/A_

## Linked tickets

[MAILPOET-4727]

## After-merge notes

_N/A_

[MAILPOET-4727]: https://mailpoet.atlassian.net/browse/MAILPOET-4727?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2022-10-21 10:50 UTC, cleacos commented on mailpoet/lib/Config/SubscriberChangesNotifier.php
> +      $minTimestamp = min($this->createdSubscriberIds);
This array could be empty, and `min` requires at least one element. E_WARNING.

2022-10-21 10:51 UTC, cleacos commented on mailpoet/lib/Config/SubscriberChangesNotifier.php
> +      if ($minTimestamp) {
Same here for a empty array

2022-10-21 10:55 UTC, cleacos commented on mailpoet/lib/Config/SubscriberChangesNotifier.php
> +      $this->wp->doAction(SubscriberEntity::HOOK_MULTIPLE_SUBSCRIBERS_DELETED, array_keys($this->deletedSubscriberIds));
if there are no deleted subscribers... we will get the hook `HOOK_MULTIPLE_SUBSCRIBERS_DELETED` after calling to the `notify()` method, won't we?

2022-10-24 12:17 UTC, cleacos commented
I took a look at the code, and it looks good. Woody will test it in our PR. Thank you.

2022-10-25 11:42 UTC, lysyjan commented
@costasovo Feel free to reassign this PR if you are too busy.

2022-10-26 08:28 UTC, costasovo requested changes
Thanks for implementing those hooks! I like that the logic for notifying is in the notification service.

I think I've found a potential issue with a timestamp of a change. Please see my comment.

I see that the PR covers changes done for individual Subscriber entities via the event listener and also bulk changes done via the Subscribers Repository. But I think we have more places where we update Subscribers places that are not covered by this PR.

- [WordPress users sync](https://github.com/mailpoet/mailpoet/blob/24cca1ba04a9ab78250e62f7ec62aff78ba217b1/mailpoet/lib/Segments/WP.php#L211-L225)
- [Subscribers Import](https://github.com/mailpoet/mailpoet/blob/daa5575d876cc1087bae806f5b300992dd875e94/mailpoet/lib/Subscribers/ImportExport/Import/Import.php#L490-L546)
- [WooCommerce Customers batch sync](https://github.com/mailpoet/mailpoet/blob/1010b64c05dba38f62cad0933ec32e7e2a83836f/mailpoet/lib/Segments/WooCommerce.php#L173-L193)

There might be some more. Do we plan to cover those later?

2022-10-26 08:28 UTC, costasovo commented on mailpoet/lib/Config/SubscriberChangesNotifier.php
> +    $this->createdSubscriberIds[$subscriberId] = Carbon::createFromTimestamp($this->wp->currentTime('timestamp'), 'UTC');
I think that the resulting timestamp might not be UTC here.
WP function `current_time` takes a second argument `$gmt` which is false by default.
If the $gmt is false it adds the offset from WP option.  [See the source](https://developer.wordpress.org/reference/functions/current_time/#source)

2022-10-26 17:23 UTC, lysyjan commented
@costasovo I added new commits that should cover changes in import and synchronization from WP and WC.

2022-10-26 17:46 UTC, costasovo approved these changes
LGTM! 👍

2022-10-27 07:31 UTC, veljkho approved these changes

2022-10-27 07:31 UTC, merged