Enforce user selection for welcome wizard privacy and data sharing - MAILPOET-4681
mailpoet/mailpoet pull request #4469
Opened 2022-10-31 07:14 UTC by triple0t

## Description

Enforce user selection for welcome wizard privacy and data sharing page

We are making the two buttons mandatory. Users have to select either yes or no before they can proceed with the welcome wizard.

## Code review notes

Kind reminder to run `./do compile:js`

## QA notes

Check ticket description

## Linked tickets

[MAILPOET-4681](https://mailpoet.atlassian.net/browse/MAILPOET-4681)

2022-10-31 11:20 UTC, samnajian requested changes

2022-10-31 11:20 UTC, samnajian commented on mailpoet/assets/js/src/wizard/steps/usage_tracking_step.jsx
> +const checkForNullOrUndefined = (value) =>
```suggestion
const isNullOrUndefined = (value) =>
```

2022-10-31 18:48 UTC, samnajian approved these changes
LGTM!

2022-11-03 09:32 UTC, Aschepikov approved these changes
Verified, GJ!

2022-11-07 13:17 UTC, Aschepikov approved these changes
Verified, GJ!

2022-11-07 13:17 UTC, merged