Translation string fixes [MAILPOET-4758]
mailpoet/mailpoet pull request #4472
Opened 2022-11-01 15:42 UTC by JanJakes

## Description

Just a couple of string fixes based on discussions in #mailpoet-translations.

## Code review notes

_N/A_

## QA notes

_N/A_

## Linked PRs

_N/A_

## Linked tickets

[MAILPOET-4758]

## After-merge notes

_N/A_

2022-11-01 17:05 UTC, johnolek requested changes
Looks good overall! Just a couple of minor things

2022-11-01 17:05 UTC, johnolek commented on mailpoet/lib/Config/PopulatorData/Templates/WelcomeBlank1Column.php
> +                    "text" => __("<h1 style=\"text-align: center;\"><strong>Hi, new subscriber!</strong></h1>\n<p>&nbsp;</p>\n<p>[subscriber:firstname | default:Subscriber],</p>\n<p>&nbsp;</p>\n<p>Yo
(this comment also applies to the same content in the 12 column file)

We should probably update these to be the new URLs (and sometimes different titles) under `/blog/` so we don't have to rely on 301 redirects, which aren't working for one of the links:

https://www.mailpoet.com/blog/the-importance-of-focus-when-writing/
5 Ways to Improve Your Focus When Writing

---

https://www.mailpoet.com/blog/write-advice-motivation/
Title is the same for this one

---

https://www.mailpoet.com/blog/writing-next-great-email-subject-line/
Writing Your Next Great Email Subject Line

I'm assuming this is the correct article. The original, `https://www.mailpoet.com/write-great-subject-line`, 301s to `https://www.mailpoet.com/blog/write-great-subject-line/`, which 301s to `https://www.mailpoet.com/?p=5289`, which 404s.

2022-11-01 17:05 UTC, johnolek commented on mailpoet/assets/js/src/automation/editor/components/header/document_actions.tsx
> +                      {__('Editing workflow:', 'mailpoet')}
Should we not be referring to it as an automation in user-facing text like this?

2022-11-02 20:40 UTC, JanJakes commented on mailpoet/lib/Config/PopulatorData/Templates/WelcomeBlank1Column.php
> +                    "text" => __("<h1 style=\"text-align: center;\"><strong>Hi, new subscriber!</strong></h1>\n<p>&nbsp;</p>\n<p>[subscriber:firstname | default:Subscriber],</p>\n<p>&nbsp;</p>\n<p>Yo
Good catch!

2022-11-03 15:20 UTC, JanJakes commented
@johnolek I just rebased both this and premium. There were things merged to `trunk` today, so I had to recheck the strings.

2022-11-03 16:29 UTC, johnolek approved these changes, later dismissed
Looks good to me!

2022-11-04 08:51 UTC, websupporter approved these changes
lgtm

2022-11-04 08:51 UTC, merged