Fix Form Editor scrollbars [MAILPOET-4607]
mailpoet/mailpoet pull request #4679
Opened 2023-01-25 06:50 UTC by NeosinneR

## Description

Remove the redundant close button in the Form Editor sidebar header, which was causing vertical scrollbars to be present in all areas (sidebar, content and settings). 

Also added animation on the toggle button in the top bar when opening/closing the sidebar.

## Code review notes

_N/A_

## QA notes

_N/A_

## Linked PRs

_N/A_

## Linked tickets

[MAILPOET-4607]

## After-merge notes

_N/A_

2023-01-25 07:36 UTC, costasovo requested changes
Thank you for the fix!

I found that without the button, there is no way (at least I couldn't find it) to close the inserter on a small screen.

<img width="423" alt="Screenshot 2023-01-25 at 8 29 44" src="https://user-images.githubusercontent.com/1082140/214505181-50516fde-4555-4307-8b43-a90f8cdf633c.png">

I don't expect users to design forms fully on mobile, but they may want to adjust display settings and labels or even add a simple field. Maybe instead of removing the button, we could just hide it on a big screen?

2023-01-25 10:07 UTC, NeosinneR commented
@costasovo nice catch. I updated the PR to only hide it on big screen, so it's still visible on small screens

2023-01-25 11:25 UTC, costasovo approved these changes
Thank you! 👍

2023-01-26 13:45 UTC, Aschepikov approved these changes
GJ!

2023-01-26 13:45 UTC, merged