Sending gets stuck if after scheduling the susbcribers unsubscribe or get deleted [MAILPOET-5134]
mailpoet/mailpoet pull request #4797
Opened 2023-03-16 20:14 UTC by samnajian

## Description

This PR invalidates scheduled tasks when in sending time determines they have no more subscriptions.

## QA notes

- Schedule a newsletter with one subscriber
- Unsubscribe the subscribers of the list selected in previous step
- (optional) Change the schedule time via in DB to reduce waiting
- Verify this task is not in `Running tasks` table under Help > System Status.

## Linked tickets

 [MAILPOET-5134]

2023-03-21 13:04 UTC, costasovo requested changes
Thank you for addressing this issue. 👍 I found only a small issue.

2023-03-21 13:04 UTC, costasovo commented on mailpoet/tests/integration/Cron/Workers/SendingQueue/SendingQueueTest.php
> +    $segmentName = 'List ' . Security::generateRandomString();
We do reset DB before every single test, so there is no need to generate random names, and if you don't need specific names, you can go with the default. But using random is perfectly fine. No need to change it.

2023-03-21 13:04 UTC, costasovo commented on mailpoet/lib/Cron/Workers/SendingQueue/SendingQueue.php
> +    if ($subscriberBatches->count() == 0) {
We prefer using === to check also the type. Could you please update it?

2023-03-30 09:05 UTC, costasovo approved these changes
LGTM! 👍

2023-04-03 09:53 UTC, Aschepikov approved these changes
GJ!

2023-04-03 09:53 UTC, merged