Import sql to local Docker environment
mailpoet/mailpoet pull request #4820
Opened 2023-03-29 14:54 UTC by veljkho

## Description

_N/A_

## Code review notes

_N/A_

## QA notes

_N/A_

## Linked PRs

_N/A_

## Linked tickets

_N/A_

## After-merge notes

_N/A_

2023-04-04 19:32 UTC, samnajian requested changes
The test runs properly, but I couldn't find screenshots in `_screenshots`, am I missing something? also please note the comment about the `env`

2023-04-04 19:32 UTC, samnajian commented on mailpoet/RoboFile.php
> +    $url = getenv('WP_TEST_PERFORMANCE_DATA_URL');
Please add `WP_TEST_PERFORMANCE_DATA_URL` to env.sample as well

2023-04-05 06:39 UTC, veljkho commented on mailpoet/RoboFile.php
> +    $url = getenv('WP_TEST_PERFORMANCE_DATA_URL');
Done. 👍

2023-04-05 06:40 UTC, veljkho commented
> The test runs properly, but I couldn't find screenshots in `_screenshots`, am I missing something? also please note the comment about the `env`

This is weird @samnajian ... What command did you run and what's the output in the end? If you used the one from the description, please see `Checks` line and it should be 14✓ 0X...

2023-04-05 09:31 UTC, samnajian approved these changes
Decided to approve since it's passing on the CI and seems like my local issue.

2023-04-05 09:32 UTC, merged