Add the boxes and the check boxes
mailpoet/mailpoet pull request #4839
Opened 2023-04-07 17:43 UTC by samnajian

[MAILPOET-5193]

## Description

_N/A_

## Code review notes

_N/A_

## QA notes

_N/A_

## Linked PRs

_N/A_

## Linked tickets

_N/A_

## After-merge notes

_N/A_

2023-04-11 09:26 UTC, costasovo requested changes
Looks good! I found just a little issue in a translation string.

2023-04-11 09:26 UTC, costasovo commented on mailpoet/assets/js/src/newsletter_editor/blocks/sidebar/brandStyles.tsx
> +        {__('Choose a style')} <i className="mailpoet_info" />
I think you need to add the domain parameter here.

`__('Choose a style', 'mailpoet')`

2023-04-11 09:40 UTC, samnajian commented on mailpoet/assets/js/src/newsletter_editor/blocks/sidebar/brandStyles.tsx
> +        {__('Choose a style')} <i className="mailpoet_info" />
Fixed in 03edc465caac8e494a895aa5370d34c414534dee

2023-04-11 10:46 UTC, costasovo approved these changes, later dismissed
👍

2023-04-11 11:34 UTC, costasovo commented
@samnajian I already approved the PR, but when I returned to my browser, I noticed there was a react warning coming from the new code.

I guess this is something we should address.

![Screenshot 2023-04-11 at 13 31 08](https://user-images.githubusercontent.com/1082140/231150058-bc105b36-e3f5-4501-84e0-d8e6e82e98e9.png)

2023-04-11 12:54 UTC, samnajian commented
> @samnajian I already approved the PR, but when I returned to my browser, I noticed there was a react warning coming from the new code.
> 
> I guess this is something we should address.
> 
> ![Screenshot 2023-04-11 at 13 31 08](https://user-images.githubusercontent.com/1082140/231150058-bc105b36-e3f5-4501-84e0-d8e6e82e98e9.png)

Fixed in f6ae74d3cf4224ec72178e16d88356256fd25507

2023-04-12 08:25 UTC, costasovo approved these changes
Thanks for fixing the warning!

2023-04-12 09:20 UTC, Aschepikov approved these changes
GJ!

2023-04-12 09:20 UTC, merged