Split Lists page into Lists and Segments [MAILPOET-5392]
mailpoet/mailpoet pull request #5019
Opened 2023-06-23 14:00 UTC by rodrigoprimo

## Description

Creating this PR as a draft while waiting for #4999 to be merged.

## Code review notes

_N/A_

## QA notes

_N/A_

## Linked PRs

_N/A_

## Linked tickets

[MAILPOET-5392]

## After-merge notes

_N/A_

## Tasks

- [ ] I followed [best practices](https://codex.wordpress.org/I18n_for_WordPress_Developers) for translations
- [ ] I added sufficient test coverage
- [ ] I embraced TypeScript by either creating new files in TypeScript or converting existing JavaScript files when making changes

2023-07-09 21:09 UTC, NeosinneR commented
@rodrigoprimo as Jan is AFK for two weeks, I reassigned this PR to @johnolek

2023-07-10 12:03 UTC, rodrigoprimo commented
Thanks, @NeosinneR. I completely missed that he is AFK. I saw his AFK status on Slack but since there was no description, I wrongly assumed that he was away just for a few hours or for the day.

2023-07-10 19:24 UTC, johnolek requested changes
Overall this looks good to me -- nice work!

The one thing I would prefer to have changed is the render method. I think we should avoid loading all the data we need for segments if we know we're rendering lists.

Regarding the naming, although I like the idea of using "static segments," I don't like the idea of introducing another term without getting rid of the old one. It seems like it could just make it more confusing for someone who wasn't familiar with the naming. Would it be too painful to split it into `dynamic_segments` and `segments` for now (or something similar that uses the current naming), and hopefully we can refactor everything together sometime later?

I think the `app` naming is very clear, but the convention seems to be using the same name as the directory as the filename, like `homepage/homepage` and wizard/wizard`, so I think if we could stick to that convention it would be nice, but not necessary.

2023-07-10 19:24 UTC, johnolek commented on mailpoet/lib/AdminPages/Pages/Segments.php
> +  public function render(string $type) {
Did you consider creating separate `render` methods for static vs dynamic segments? It seems like we would be loading a lot of extra stuff that the static segments don't require at all.

2023-07-10 19:24 UTC, johnolek commented on mailpoet/assets/js/src/webpack_admin_index.tsx
> +import 'segments/static/app';
For consistency this should probably include the side effect comment too

2023-07-11 15:11 UTC, rodrigoprimo commented on mailpoet/lib/AdminPages/Pages/Segments.php
> +  public function render(string $type) {
At first, I didn't want to touch this part as we were already loading everything for both pages, and I was afraid splitting was going to be hard and could potentially break things.

I went ahead and created separate `render` methods. One for each page. The only part that I kept together is the translations as splitting them would be more involved and probably not worth it.

That being said, I doubled down on using `static` and `dynamic` segments. More on that in a separate comment.

2023-07-11 15:11 UTC, rodrigoprimo commented on mailpoet/assets/js/src/webpack_admin_index.tsx
> +import 'segments/static/app';
:+1:

2023-07-11 15:26 UTC, rodrigoprimo commented
Thanks for the review, @johnolek!

> Regarding the naming, although I like the idea of using "static segments," I don't like the idea of introducing another term without getting rid of the old one. It seems like it could just make it more confusing for someone who wasn't familiar with the naming. Would it be too painful to split it into dynamic_segments and segments for now (or something similar that uses the current naming), and hopefully we can refactor everything together sometime later?

I'm inclined to think that using `static` and `dynamic` to differentiate the types of segments is a bit better than `dynamic_segments` and `segments` and reduces a bit the confusion that is already present instead of making it worst. I say this because at least when you see `static` or `dynamic`, there is no confusion as to which is which. The same can't be said about `dynamic_segments` and `segments`. When seeing just `segments` it is not easy to know if it refers only to the static segments or if it refers to both types of segments.

We are already using `static` and `dynamic` in a few parts of the codebase (but I agree that it is not widely adopted). Here are a few examples:

https://github.com/mailpoet/mailpoet/blob/acbd7fe7235edd143d4f09a47069419f0df3a6a1/mailpoet/lib/AdminPages/Pages/Segments.php#L98
https://github.com/mailpoet/mailpoet/blob/acbd7fe7235edd143d4f09a47069419f0df3a6a1/mailpoet/lib/Segments/SubscribersFinder.php#L92
https://github.com/mailpoet/mailpoet/blob/acbd7fe7235edd143d4f09a47069419f0df3a6a1/mailpoet/assets/js/src/segments/dynamic/store/selectors.ts#L47
https://github.com/mailpoet/mailpoet/blob/acbd7fe7235edd143d4f09a47069419f0df3a6a1/mailpoet/assets/js/src/segments/dynamic/dynamic_segments_filters/fields/subscriber/subscriber_subscribed_to_list.tsx#L14

Happy to chat further about this. I don't see an easy solution. My hope is that using `static` and `dynamic` in this PR makes the code a bit better and not worst, but I can definitely be missing a few things.

2023-07-11 16:26 UTC, johnolek commented
@rodrigoprimo Thanks for elaborating about the static terminology, and I'm happy to leave it the way you have it. I didn't even realize/remember that there are other places where we're already using the static term.

I definitely agree that `static` and `dynamic` is clearer than `segments` and `dynamic_segments`, and I wish that we were using those terms everywhere. I think it can be confusing when you have 2 potential ways of referring to the same thing in the codebase, but you're right that in this case it's probably more confusing to continue using an ambiguous term like `segment`.

Maybe it would make for a good maintenance ticket to try to standardize the terminology and make sure we're using the static terminology everywhere.

2023-07-11 18:59 UTC, rodrigoprimo commented
@johnolek, I assigned this PR back to you and I believe it is ready for a final review.

I agree that we should create a maintenance ticket to look into the naming problem with segments.

2023-07-11 19:18 UTC, johnolek approved these changes, later dismissed
Looks good to me. Nice work!

By the way, I updated the description to point to the new premium PR with the matching branch name.

2023-07-11 20:52 UTC, rodrigoprimo commented
> By the way, I updated the description to point to the new premium PR with
the matching branch name.

Thanks!

On Tue, Jul 11, 2023 at 4:18 PM John Oleksowicz ***@***.***>
wrote:

> ***@***.**** approved this pull request.
>
> Looks good to me. Nice work!
>
> By the way, I updated the description to point to the new premium PR with
> the matching branch name.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/mailpoet/mailpoet/pull/5019#pullrequestreview-1525010222>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAS3HZD6GPNEN42A6HKU6TXPWRIRANCNFSM6AAAAAAZRTPMB4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-07-12 09:12 UTC, Aschepikov commented
HI @rodrigoprimo there are some conflicts can you resolve them pls

2023-07-12 16:41 UTC, rodrigoprimo commented
@Aschepikov, I just fixed the conflicts. I had to also update a few of the acceptance tests when rebasing as new acceptance tests were introduced to `trunk` using the old page structure.

Also, I should have made it more clear that the idea was to merge https://github.com/mailpoet/mailpoet-premium/pull/748 together with this PR (@veljkho). Since #748 was already merged, the acceptance tests for premium are failing. This shouldn't be a problem if we merge this PR soon, but please let me know if that is not possible and I will probably revert #748,

2023-07-12 16:46 UTC, Aschepikov approved these changes
GJ!

2023-07-12 16:46 UTC, merged