Mailpoet 5413/number of reviews filter
mailpoet/mailpoet pull request #5064
Opened 2023-07-20 21:31 UTC by johnolek

## Description

WooCommerce number of reviews filter for dynamic segments.

## Code review notes

_N/A_

## QA notes

_N/A_

## Linked PRs

_N/A_

## Linked tickets

_N/A_

## After-merge notes

_N/A_

## Tasks

- [x] I followed [best practices](https://codex.wordpress.org/I18n_for_WordPress_Developers) for translations
- [x] I added sufficient test coverage
- [x] I embraced TypeScript by either creating new files in TypeScript or converting existing JavaScript files when making changes

2023-08-03 06:49 UTC, triple0t requested changes
Hi @johnolek 
I'm getting this error in the console.
<img width="1792" alt="Screenshot 2023-08-03 at 7 44 43 AM" src="https://github.com/mailpoet/mailpoet/assets/30554163/1f371e5c-8e91-4d81-965f-b7b38145537f">

Full log
[mp3.localhost-1691045187137.log](https://github.com/mailpoet/mailpoet/files/12247708/mp3.localhost-1691045187137.log)

The filter wasn’t working... probably due to the error.

Can you take a look?

2023-08-03 16:31 UTC, johnolek commented
@triple0t I apologize for not testing this better myself before requesting your review!

I'm guessing that the main issue might have actually been an oversight on my part where I wasn't setting the default `rating` when adding a new filter in the builder. 

The warning shouldn't have been preventing the filter from working, but you would have needed to switch from the `Any` rating to something else before validation would have worked, because as far as React was concerned the filter had no `rating` value.

I fixed these issues in 89df118a2b3dcd55c3dbea6171eb1d79b1036a99, and I also decided to extract some of the strings into enums just as a general best practice.

I think this should be truly ready for review now. Sorry again!

2023-08-04 17:05 UTC, triple0t commented
> I apologize for not testing this better myself before requesting your review!
> 
> I'm guessing that the main issue might have actually been an oversight on my part where I wasn't setting the default `rating` when adding a new filter in the builder.
> 
> The warning shouldn't have been preventing the filter from working, but you would have needed to switch from the `Any` rating to something else before validation would have worked, because as far as React was concerned the filter had no `rating` value.
> 
> I fixed these issues in [89df118](https://github.com/mailpoet/mailpoet/commit/89df118a2b3dcd55c3dbea6171eb1d79b1036a99), and I also decided to extract some of the strings into enums just as a general best practice.
> 
> I think this should be truly ready for review now. Sorry again!

Not a problem, John. 

Thank you for fixing the issue.

My local environmental might have issues. I'm unable to Add ratings to products.

I'm approving this PR; the code looks good. 👍

2023-08-04 17:05 UTC, triple0t approved these changes

2023-08-04 21:21 UTC, johnolek commented
Thanks for the review, @triple0t.

FYI QA team, I just added the `priority in QA` label because there are a couple other PRs now that depend on some changes made in this one.

2023-08-07 09:06 UTC, Aschepikov approved these changes
GJ!

2023-08-07 09:06 UTC, merged