Updated 600,000 to 700,000 active installs [MAILPOET-5541]
mailpoet/mailpoet pull request #5115
Opened 2023-08-21 20:36 UTC by NeosinneR

## Description

_N/A_

## Code review notes

_N/A_

## QA notes

_N/A_

## Linked PRs

_N/A_

## Linked tickets

[MAILPOET-5541]

## After-merge notes

_N/A_

## Tasks

- [x] 🚫 I followed [best practices](https://codex.wordpress.org/I18n_for_WordPress_Developers) for translations
- [x] 🚫 I added sufficient test coverage
- [x] 🚫 I embraced TypeScript by either creating new files in TypeScript or converting existing JavaScript files when making changes

2023-08-22 03:47 UTC, websupporter commented on mailpoet/assets/js/src/landingpage/content.tsx
> +          ).replace('[count]', '700,000+')}
We usually use `sprintf()`, I would also suggest a `// translators` comment before explaining the `%s` and you would need to import `sprintf()`
```suggestion
          {sprintf(__(
            'Powering email marketing for %s websites',
            'mailpoet',
          ), '700,000+')}
```

2023-08-22 03:47 UTC, websupporter requested changes
see comment above

2023-08-22 06:58 UTC, websupporter submitted a review, later dismissed
lgtm. thank you @NeosinneR

2023-08-22 07:32 UTC, NeosinneR commented
@websupporter I had to force push due to prettier failing

2023-08-22 07:49 UTC, websupporter approved these changes
lgtm.

2023-08-23 10:59 UTC, Aschepikov approved these changes
GJ!

2023-08-23 10:59 UTC, merged