Improved upgrade page [MAILPOET-5142]
mailpoet/mailpoet pull request #5306
Opened 2023-11-23 22:37 UTC by NeosinneR

## Description

Updated the upgrade page (`admin.php?page=mailpoet-upgrade`):

- Removed  `Fuel growth with a MailPoet Business plan` section.
- Removed the Agency plan section.
- Made the background white.
- Moved the top section title and description into the Business/Creator plan section.
- Updated plan features to correspond with [the pricing page](https://account.mailpoet.com/).
- Added top bar with MailPoet logo (no Updates button though). 

## Code review notes

_N/A_

## QA notes

_N/A_

## Linked PRs

_N/A_

## Linked tickets

MAILPOET-5142

## After-merge notes

_N/A_

## Tasks

- [x] I followed [best practices](https://codex.wordpress.org/I18n_for_WordPress_Developers) for translations
- [x] 🚫 I added sufficient test coverage
- [x] 🚫 I embraced TypeScript by either creating new files in TypeScript or converting existing JavaScript files when making changes

2023-11-24 06:13 UTC, websupporter commented on mailpoet/views/upgrade.html
> +  <a role="button" class="mailpoet-top-bar-logo" title="Back to section root" tabindex="0" href="admin.php?page=mailpoet-homepage">
Should be translateable

2023-11-24 06:19 UTC, websupporter requested changes
thank you @neosinner. lgtm. just one small fix.

2023-11-24 08:04 UTC, NeosinneR commented on mailpoet/views/upgrade.html
> +  <a role="button" class="mailpoet-top-bar-logo" title="Back to section root" tabindex="0" href="admin.php?page=mailpoet-homepage">
Good catch, fixed

2023-11-24 09:46 UTC, websupporter approved these changes
lgtm. thank you @NeosinneR

2023-11-27 11:00 UTC, Aschepikov approved these changes
GJ!

2023-11-27 11:00 UTC, merged