Update email block core/paragraph renderer [MAILPOET-5642]
mailpoet/mailpoet pull request #5346
Opened 2023-12-18 13:24 UTC by lysyjan

## Description

We had a simple core/paragraph block render that didn't support all possible configurations. In this renderer iteration, we add the possibility of text alignment and rendering compatibility across email clients.

## Code review notes

_N/A_

## QA notes

QA could be skipped here, I would let the decision on the reviewer.

## Linked PRs

_N/A_

## Linked tickets

[MAILPOET-5642]

## After-merge notes

_N/A_

## Tasks

- [x] I followed [best practices](https://codex.wordpress.org/I18n_for_WordPress_Developers) for translations
- [x] I added sufficient test coverage
- [x] I embraced TypeScript by either creating new files in TypeScript or converting existing JavaScript files when making changes

2024-01-03 15:10 UTC, costasovo requested changes
@lysyjan Thank you for adding the support for the paragraph block!

I added a couple of comments. Just details.

Btw. I noticed that the formatting options for the paragraph in the email editor are limited compared to the formatting options in the post editor. I think it makes sense that we can't support all the options for emails. But maybe we could add support at least for `Highlight` because I find this one quite usable. What do you think? It would be an extra ticket...
![Screenshot 2024-01-03 at 16 07 14](https://github.com/mailpoet/mailpoet/assets/1082140/cb0bf201-a061-40c1-baf2-53a6c55db246)

2024-01-03 15:10 UTC, costasovo commented on mailpoet/lib/EmailEditor/Integrations/Core/Renderer/Blocks/Paragraph.php
> +        $colorRegex = "/--wp--preset--color--$colorKey: (#[0-9a-fA-F]{6});/";
Why are we adding `--wp--preset--color--` here? Is that a convention for specifying colors in block themes? Is it documented somewhere? I think it would be helpful to have a comment explaining this here. Or maybe a comment describing a bit higher level how we get the color values. 🙏

2024-01-03 15:10 UTC, costasovo commented on mailpoet/lib/EmailEditor/Integrations/Core/Renderer/Blocks/Paragraph.php
> +  private function removePaddingFromElement($blockContent, array $tag) {
I guess we could add a return typehit here

2024-01-03 15:10 UTC, costasovo commented on mailpoet/lib/EmailEditor/Engine/Renderer/Preprocessors/BlocksWidthPreprocessor.php
> -      if (!in_array($block['blockName'], self::BLOCKS_WITHOUT_WIDTH, true)) {
It seems that this change made BLOCKS_WITHOUT_WIDTH constant unused. It would be better to remove it.

2024-01-04 11:34 UTC, lysyjan commented
@costasovo Thank you for your review. I addressed all your remarks in the three new commits.

> Btw. I noticed that the formatting options for the paragraph in the email editor are limited compared to the formatting options in the post editor. I think it makes sense that we can't support all the options for emails. But maybe we could add support at least for Highlight because I find this one quite usable. What do you think? It would be an extra ticket...

I agree with you. [By the comment in the file](https://github.com/mailpoet/mailpoet/blob/4567c6d3c1a1564e6de355d634576ac40cbe7dcb/mailpoet/assets/js/src/email-editor/engine/blocks/core/rich-text.ts#L17-L18) it looks we want to add the support later. So, creating a follow-up ticket makes sense to me.

2024-01-05 09:16 UTC, costasovo approved these changes
Thanks for the changes and the comment! The comment will help me to recall why we use the prefix in the future.

2024-01-05 09:17 UTC, merged