Add sender domain authentication task for new users [MAILPOET-5781]
mailpoet/mailpoet pull request #5389
Opened 2024-01-18 13:57 UTC by alex-mpoet

## Description

Notes:
1. I've edited the task description string as per Figma file comment.
2. After the task is clicked, the domain authorization modal is shown on the Settings page after a redirection.

## Code review notes

_N/A_

## QA notes

_N/A_

## Linked PRs

_N/A_

## Linked tickets

[MAILPOET-5781]

## After-merge notes

_N/A_

## Tasks

- [x] I followed [best practices](https://codex.wordpress.org/I18n_for_WordPress_Developers) for translations
- [x] I added sufficient test coverage
- [x] I embraced TypeScript by either creating new files in TypeScript or converting existing JavaScript files when making changes

2024-01-19 18:31 UTC, johnolek requested changes
There's one small typo to fix.

The ticket says `Clicking on the task list will open the modal or take them to admin.php?page=mailpoet-settings#/basics if they are using a free email address.`

My interpretation is that we want to open the modal on the homepage, but in this implementation it looks like we always navigate to the settings page and we'll open the modal there if the user isn't using a known free email.

The ticket says implementation can be modified and it definitely works fine how you have it, but I wanted to confirm it's what we want.

2024-01-19 18:31 UTC, johnolek commented on mailpoet/assets/js/src/settings/pages/basics/basics.tsx
> +  const { showModal } = useParams<{ showModal: string }>();
I think the typing for showModal is slightly off because it's optional in the route, so it could be `undefined` instead of a string. This might be a moot point.

2024-01-19 18:31 UTC, johnolek commented on mailpoet/views/homepage.html
> +  'improveDeliveryRates': __('Improve email delivery dates'),
```suggestion
  'improveDeliveryRates': __('Improve email delivery rates'),
```

2024-01-22 08:30 UTC, alex-mpoet commented on mailpoet/views/homepage.html
> +  'improveDeliveryRates': __('Improve email delivery dates'),
Good catch, fixed!

2024-01-22 09:21 UTC, alex-mpoet commented on mailpoet/assets/js/src/settings/pages/basics/basics.tsx
> +  const { showModal } = useParams<{ showModal: string }>();
Technically you're correct. But it's done the same way in the "Send with..." tab and things seem to work fine. We only use strict comparison for these optional vars.

2024-01-22 09:30 UTC, alex-mpoet commented
@johnolek 

> My interpretation is that we want to open the modal on the homepage, but in this implementation it looks like we always navigate to the settings page and we'll open the modal there if the user isn't using a known free email.

Yes, I have mentioned this in my note number 2. I've did it this way because it was easier to implement (`Task` component doesn't support modals, only links), but if this is critical, it can be reworked. @brezocordero Do you think navigating to the settings page and opening the domain auth modal there after clicking on the task would work from the UX standpoint?

2024-01-22 16:54 UTC, brezocordero commented
> Do you think navigating to the settings page and opening the domain auth modal there after clicking on the task would work from the UX standpoint?

If it is very complex to open the modal from the task list, I would go ahead with this solution.
From my point of view, this alternative also works. Opening the modal on the settings page gives context to the action and they could also check the reply-to address.

I would like to have @shivanarrthine input as this is different from the [design](https://www.figma.com/file/woLQC5fKEGnyxllTudBEHE/Sender-domain-authentication?type=design&node-id=351-33008&mode=dev).

2024-01-23 06:43 UTC, shivanarrthine commented
> If it is very complex to open the modal from the task list, I would go ahead with this solution.
From my point of view, this alternative also works. Opening the modal on the settings page gives context to the action and they could also check the reply-to address.

Agreeing with @brezocordero. I think it's fine to go to the settings page with the modal open.

2024-01-23 14:52 UTC, johnolek approved these changes

2024-01-23 14:52 UTC, johnolek commented
Thanks for your input, @brezocordero and @shivanarrthine!

2024-01-29 12:27 UTC, Aschepikov approved these changes
GJ!

2024-01-29 12:27 UTC, merged