Remove escapeHtml when rendering list titles in React [MAILPOET-5842]
mailpoet/mailpoet pull request #5459
Opened 2024-02-27 16:56 UTC by mikejolley

Escaping is not required when rendering titles in react components. HTML is escaped automatically unless you use a component like `RawHTML` or the `dangerouslySetInnerHTML` attribute.

[MAILPOET-5842]

Fixes #5384

## Description

Removes usages of `escapeHtml` when rendering data inside React components. `escapeHtml` is still required when rendering notices—I left these as is.

This issue was introduced in https://github.com/mailpoet/mailpoet/commit/d52dfa215c46e370f875680f1a14db77f97da589.

## Code review notes

_N/A_

## QA notes

To test:

1. Go to MailPoet > Lists
2. Edit a list
3. Add the `&` character to the list title and the list description. Save the list.
4. Back on MailPoet > Lists, look at the items in the table. The `&` should be rendered as `&`, not `&amp;`.
5. Trash the list. The `&` should be rendered as `&`, not `&amp;` in the notice.

## Linked PRs

_N/A_

## Linked tickets

[[MAILPOET-5842]](https://mailpoet.atlassian.net/browse/MAILPOET-5842)

## After-merge notes

_N/A_

## Tasks

- [x] I followed [best practices](https://codex.wordpress.org/I18n_for_WordPress_Developers) for translations
- [ ] I added sufficient test coverage
- [ ] I embraced TypeScript by either creating new files in TypeScript or converting existing JavaScript files when making changes

2024-02-28 08:49 UTC, pavel-mailpoet approved these changes
Great job on your first pull request! I'm looking forward to seeing more of your work.

2024-03-08 11:14 UTC, veljkho requested changes
Hi @mikejolley 
I see `&amp;` in [the listing when saved](https://d.pr/i/9S7Kez). Inside the edit page it is good. Do we want to fix it also for the listing page visibility, I feel it's not the best behavior to leave it there.

2024-03-11 11:00 UTC, mikejolley commented
@veljkho Thats exactly what this PR does fix:

![Screenshot 2024-03-11 at 10 59 54](https://github.com/mailpoet/mailpoet/assets/90977/fac9a375-1353-4a57-aebe-cae383a1066b)

I think you forgot the build step. `./do compile:js`.

2024-03-12 08:38 UTC, veljkho commented
Looks like a cache issue. This is now verified, thanks for rechecking. I will merge after the today's release.

2024-03-12 08:38 UTC, veljkho approved these changes

2024-03-13 08:38 UTC, merged