Fix abandoned cart task from product discovery on homepage [MAILPOET-5847][MAILPOET-5848]
mailpoet/mailpoet pull request #5668
Opened 2024-06-19 15:34 UTC by lysyjan

## Description

This PR fixes two issues:
- The link for the `Set up an abandoned cart email` item on the homepage
- The condition when the item is marked as done

## Code review notes

- I was considering if the condition from the NewsletterRepository class should be changed to equal with the new type, but in the end, I decided to make it backward compatible. This means that we detect if the abandoned cart emails with old and new types.

## QA notes

There are two parts to the check:
1. Check that the link for the `Set up an abandoned cart email` item redirects to the page with automation templates
2. When the automation for an abandoned cart is created, the task should be marked as done

## Linked PRs

_N/A_

## Linked tickets

[MAILPOET-5847]
[MAILPOET-5848]

## After-merge notes

_N/A_

## Tasks

- [x] I followed [best practices](https://codex.wordpress.org/I18n_for_WordPress_Developers) for translations
- [x] I added sufficient test coverage
- [x] I embraced TypeScript by either creating new files in TypeScript or converting existing JavaScript files when making changes

2024-06-20 07:20 UTC, NeosinneR requested changes
@lysyjan the code looks good, but I'd like to propose a small change to make this more useful for users.

I know this wasn't mentioned specifically in the ticket, but previously the link led directly to setting up abandoned cart email (`mailpoet-newsletters#/new/woocommerce/woocommerce_abandoned_shopping_cart/conditions`). I think we should keep this functionality and link to `Abandoned cart` tab on the templates page. 

<img width="727" alt="Screenshot 2024-06-20 at 09 17 27" src="https://github.com/mailpoet/mailpoet/assets/470616/c08d98d4-0250-42f6-9830-a89e5fa4141c">

Currently, there isn't a way to do that, but with a simple change, it'd be possible to set initial tab via URL (`admin.php?page=mailpoet-automation-templates&initialTab=abandoned-cart`).

<img width="621" alt="Screenshot 2024-06-20 at 09 14 01" src="https://github.com/mailpoet/mailpoet/assets/470616/3106dae8-a662-458b-8afc-abf47ce92947">

What do you think?

2024-06-20 07:46 UTC, lysyjan commented
@NeosinneR I agree. I was considering it but decided it was out of scope. Nevertheless, this pull request is not too big, so we can add it.

2024-06-20 13:55 UTC, lysyjan commented
@NeosinneR I added two new commits that address your suggestion.

2024-06-20 14:03 UTC, NeosinneR approved these changes
Thanks for the updates, @lysyjan. Works like a charm.

2024-06-21 12:53 UTC, veljkho approved these changes
Works as expected!

2024-06-21 12:53 UTC, merged