Upgrade codemirror [MAILPOET-5483]
mailpoet/mailpoet pull request #5689
Opened 2024-06-26 07:50 UTC by pavel-mailpoet

## Description

Upgrade the CodeMirror dependency

## Code review notes

I used a new package react-codemirror. The library considers using the old method with [TextArea](https://codemirror.net/docs/migration/#codemirror.fromtextarea) as a hack and discourages from using it. The original Code Mirror is a vanilla library and works with DOM, so in order to retain the functionality, I had to either use a lot of DOM manipulation or a library. I think the library react-codemirror is a good choice right now; it is popular and maintained.

I removed the use of a theme to limit the number of dependencies, and the editor doesn't understand CSS. I think this is an acceptable tradeoff for our usage. 

## QA notes

The Code Mirror library is used in the form editor in the sidebar where users can edit their own CSS.

## Linked PRs

_N/A_

## Linked tickets

[MAILPOET-5483]

## After-merge notes

_N/A_

## Tasks

- [ ] I followed [best practices](https://codex.wordpress.org/I18n_for_WordPress_Developers) for translations
- [ ] I added sufficient test coverage
- [ ] I embraced TypeScript by either creating new files in TypeScript or converting existing JavaScript files when making changes

2024-06-27 14:58 UTC, lysyjan submitted a review, later dismissed
@pavel-mailpoet It looks good, but there is a conflict. Do you want to solve it now, or after QA feedback?

2024-06-28 06:07 UTC, pavel-mailpoet commented
@lysyjan I resolved the conflict.

2024-06-28 09:31 UTC, lysyjan approved these changes, later dismissed

2024-06-28 13:59 UTC, veljkho requested changes
Hi @pavel-mailpoet 
I see horizontal scrolling and pretty broken CSS like section for custom CSS in the form editor. Can you please rebase the PR and/or look for any fixes (if reproducible on your side)? https://d.pr/i/8qO3PL

2024-07-02 14:35 UTC, lysyjan commented
Hi @veljkho! I rebased this branch and tested it on my staging site, and it works as expected. Do you share more details about it? For example, browser or some specific configuration?

2024-07-08 11:09 UTC, Aschepikov commented
Hi @veljkho there is a change request can you dismiss it pls

2024-07-08 12:25 UTC, veljkho approved these changes

2024-07-08 12:29 UTC, Aschepikov approved these changes
GJ!

2024-07-08 12:29 UTC, merged