Move changelog from readme.txt to separate file [MAILPOET-6119]
mailpoet/mailpoet pull request #5697
Opened 2024-06-27 07:36 UTC by pavel-mailpoet

## Description

_N/A_

## Code review notes

See the Jira ticket for details. 

## QA notes

_N/A_

## Linked PRs

_N/A_

## Linked tickets

_N/A_

## After-merge notes

_N/A_

## Tasks

- [ ] I followed [best practices](https://codex.wordpress.org/I18n_for_WordPress_Developers) for translations
- [ ] I added sufficient test coverage
- [ ] I embraced TypeScript by either creating new files in TypeScript or converting existing JavaScript files when making changes

2024-06-27 15:46 UTC, lysyjan reviewed
@pavel-mailpoet Thanks for those changes. I added some comments; please take a look and reply when you can.

2024-06-27 15:46 UTC, lysyjan commented on mailpoet/tasks/release/ChangelogController.php
> +    if (file_exists(dirname($this->readmeFile) . DIRECTORY_SEPARATOR . 'CHANGELOG.md')) {
Please, can you explain why we need this condition? In previous commits, the changelog was added, so I would assume we don't need this condition, but maybe I'm missing something.

2024-06-27 15:46 UTC, lysyjan commented on mailpoet/tasks/release/ChangelogController.php
> +  private function updateReadmeWitchChangelogFile($heading, $changesList) {
Is it a typo here? Should be the method name `updateReadmeWithChangelogFile`?

2024-06-27 15:46 UTC, lysyjan commented on mailpoet/tasks/release/ChangelogController.php
>    private function updateReadme($heading, $changesList) {
If we rely on that both files exist, we can change this method to `updateReadmeAndChangelog` and add the changelog as a second parameter. What do you think about it? It can also remove the generated changelog file path in the new code.

2024-06-28 05:53 UTC, pavel-mailpoet commented on mailpoet/tasks/release/ChangelogController.php
> +    if (file_exists(dirname($this->readmeFile) . DIRECTORY_SEPARATOR . 'CHANGELOG.md')) {
Yes, we need this condition here. The code is used in both plugins; the changelog doesn't exist in the Premium plugin. I didn't want to check specifically for free/premium, but I made it more general.

2024-06-28 05:54 UTC, pavel-mailpoet commented on mailpoet/tasks/release/ChangelogController.php
> +  private function updateReadmeWitchChangelogFile($heading, $changesList) {
Yep, a typo, I will fix that.

2024-06-28 06:00 UTC, pavel-mailpoet commented on mailpoet/tasks/release/ChangelogController.php
>    private function updateReadme($heading, $changesList) {
Sorry, I don't think I understand what you mean. 

The name as is makes more sense to me. You are calling the function when you want to update readme. It may move the latest changelog to a new file if it exists or leave it there. However, that is an implementation detail of this function. 

Could you please elaborate?

2024-06-28 08:54 UTC, lysyjan commented on mailpoet/tasks/release/ChangelogController.php
> +    if (file_exists(dirname($this->readmeFile) . DIRECTORY_SEPARATOR . 'CHANGELOG.md')) {
Thanks, I didn't realize that.

2024-06-28 08:56 UTC, lysyjan commented on mailpoet/tasks/release/ChangelogController.php
>    private function updateReadme($heading, $changesList) {
My suggestion was based on the condition (first comment). It doesn't make sense anymore because of usage in the premium plugin.

2024-06-28 09:03 UTC, pavel-mailpoet commented on mailpoet/tasks/release/ChangelogController.php
> +  private function updateReadmeWitchChangelogFile($heading, $changesList) {
fixed

2024-06-28 10:15 UTC, lysyjan requested changes
@pavel-mailpoet I have tested your solution, and the changelog and readme should contain the latest change notes. So, we should not copy the previous version from readme to the changelog, as it is in your current solution. Does this make sense to you?

If you want, you can check it as it looks on [the WooCommerce plugin page](https://wordpress.org/plugins/woocommerce/#developers).

2024-06-28 11:56 UTC, lysyjan approved these changes
Good job! Thank you

2024-06-28 12:27 UTC, merged